"""
Channel Partner Revenue

The total revenue generated by channel partners over a given period.
"""

CHANNEL_PARTNER_REVENUE = {
    "code": "CHANNEL_PARTNER_REVENUE",
    "name": "Channel Partner Revenue",
    "description": "The total revenue generated by channel partners over a given period.",
    "formula": "Total Sales Revenue from Channel Partners",
    "calculation_formula": "Total Sales Revenue from Channel Partners",
    "category": "Channel Sales",
    "is_active": True,
    "full_kpi_definition": "Complete definition for Channel Partner Revenue to be added.",
    "trend_analysis": """



    * Increasing channel partner revenue may indicate successful onboarding of new partners or improved performance of existing partners.
    * Decreasing revenue could signal issues with partner enablement, market demand, or competitive pressures.
    
    
    
    """,
    "diagnostic_questions": """



    * Are there specific products or services that are driving the majority of channel partner revenue?
    * How does our channel partner revenue compare with industry benchmarks or with revenue from direct sales?
    
    
    
    """,
    "actionable_tips": """



    * Invest in partner training and enablement to improve their sales capabilities.
    * Regularly review and optimize the partner incentive and commission structure to align with business goals.
    * Expand the product or service offerings available to channel partners to increase revenue potential.
    
    
    
    """,
    "visualization_suggestions": """



    * Line charts showing revenue trends over time for each channel partner.
    * Pie charts to visualize the contribution of different partners to the overall revenue.
    
    
    
    """,
    "risk_warnings": """



    * Over-reliance on a small number of channel partners for the majority of revenue can pose a risk to overall business stability.
    * Declining revenue from channel partners may indicate a need for reevaluation of the partner program and relationships.
    
    
    
    """,
    "tracking_tools": """



    * Customer Relationship Management (CRM) systems to track partner interactions and revenue generation.
    * Partner Relationship Management (PRM) platforms to streamline partner communication and collaboration.
    
    
    
    """,
    "integration_points": """



    * Integrate channel partner revenue data with sales and marketing systems to understand the full customer journey and touchpoints.
    * Link revenue performance with partner management systems to align incentives and support with revenue goals.
    
    
    
    """,
    "change_impact_analysis": """



    * Increasing channel partner revenue can positively impact overall sales performance and market reach.
    * However, a decline in revenue may lead to strained partner relationships and potential loss of market share.
    
    
    
    """,
    "metadata_": {"modules": ["CHANNEL_SALES"], "source": "kpidepot.com", "import_date": "2025-11-07", "required_objects": ["Channel Conflict", "Channel Deal", "Channel Market", "Channel Partner", "Customer", "Partner Agreement", "Partner Incentive", "Partner Performance Scorecard", "Partner Portal", "Partner Training", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"], "last_validated": "2025-11-10T13:49:32.690393"},
    "required_objects": [],
    "modules": ["CHANNEL_SALES"],
    "module_code": "CHANNEL_SALES",
    "sample_data": {
        "time_series": {
                "dates": [
                        "2024-12-15",
                        "2025-01-14",
                        "2025-02-13",
                        "2025-03-15",
                        "2025-04-14",
                        "2025-05-14",
                        "2025-06-13",
                        "2025-07-13",
                        "2025-08-12",
                        "2025-09-11",
                        "2025-10-11",
                        "2025-11-10"
                ],
                "values": [
                        80822.64,
                        89854.69,
                        87605.85,
                        89939.73,
                        90692.1,
                        85528.19,
                        91592.62,
                        84399.16,
                        86931.37,
                        86581.39,
                        85754.94,
                        80894.02
                ],
                "unit": "$"
        },
        "current": {
                "value": 80894.02,
                "unit": "$",
                "change": -4860.92,
                "change_percent": -5.7,
                "trend": "stable"
        },
        "statistics": {
                "average": 86716.39,
                "min": 80822.64,
                "max": 91592.62,
                "unit": "$"
        },
        "breakdown": [
                {
                        "category": "Direct Sales",
                        "value": 27637.5,
                        "percentage": 34.2
                },
                {
                        "category": "Channel Sales",
                        "value": 11138.62,
                        "percentage": 13.8
                },
                {
                        "category": "Online Sales",
                        "value": 12179.12,
                        "percentage": 15.1
                },
                {
                        "category": "Enterprise Sales",
                        "value": 7510.45,
                        "percentage": 9.3
                },
                {
                        "category": "Other",
                        "value": 22428.33,
                        "percentage": 27.7
                }
        ],
        "metadata": {
                "generated_date": "2025-11-10T13:51:11.456116",
                "data_points": 12,
                "kpi_type": "currency",
                "kpi_name": "Channel Partner Revenue"
        }
    },
}
