"""
Channel Partner Revenue KPI

The total revenue generated by channel partners over a given period.
"""

from analytics_models import KPI

CHANNEL_PARTNER_REVENUE = KPI(
    name="Channel Partner Revenue",
    code="CHANNEL_PARTNER_REVENUE",
    category="Channel Sales",
    
    # Core Definition
    description="The total revenue generated by channel partners over a given period.",
    kpi_definition="The total revenue generated by channel partners over a given period.",
    expected_business_insights="Provides insight into the direct financial impact of partners on the company’s top line.",
    measurement_approach="Accounts for the total sales revenue generated by channel partners.",
    
    # Formula
    formula="Total Sales Revenue from Channel Partners",
    calculation_formula="Total Sales Revenue from Channel Partners",
    
    # Analysis
    trend_analysis="""
    * Increasing channel partner revenue may indicate successful onboarding of new partners or improved performance of existing partners.
    * Decreasing revenue could signal issues with partner enablement, market demand, or competitive pressures.
    """,
    diagnostic_questions="""
    * Are there specific products or services that are driving the majority of channel partner revenue?
    * How does our channel partner revenue compare with industry benchmarks or with revenue from direct sales?
    """,
    
    # Action & Visualization
    actionable_tips="""
    * Invest in partner training and enablement to improve their sales capabilities.
    * Regularly review and optimize the partner incentive and commission structure to align with business goals.
    * Expand the product or service offerings available to channel partners to increase revenue potential.
    """,
    visualization_suggestions="""
    * Line charts showing revenue trends over time for each channel partner.
    * Pie charts to visualize the contribution of different partners to the overall revenue.
    """,
    
    # Risk & Integration
    risk_warnings="""
    * Over-reliance on a small number of channel partners for the majority of revenue can pose a risk to overall business stability.
    * Declining revenue from channel partners may indicate a need for reevaluation of the partner program and relationships.
    """,
    tracking_tools="""
    * Customer Relationship Management (CRM) systems to track partner interactions and revenue generation.
    * Partner Relationship Management (PRM) platforms to streamline partner communication and collaboration.
    """,
    integration_points="""
    * Integrate channel partner revenue data with sales and marketing systems to understand the full customer journey and touchpoints.
    * Link revenue performance with partner management systems to align incentives and support with revenue goals.
    """,
    change_impact_analysis="""
    * Increasing channel partner revenue can positively impact overall sales performance and market reach.
    * However, a decline in revenue may lead to strained partner relationships and potential loss of market share.
    """,
    
    is_active=True,
    metadata_={
        "modules": ["CHANNEL_SALES"],
        "source": "kpidepot.com",
        "import_date": "2025-11-07",
        "required_objects": ["Channel Conflict", "Channel Deal", "Channel Market", "Channel Partner", "Customer", "Partner Agreement", "Partner Incentive", "Partner Performance Scorecard", "Partner Portal", "Partner Training", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"]
    }
)
