"""
Customer Profitability Analysis KPI

The analysis of the profit contribution of individual customers or customer segments.
"""

CUSTOMER_PROFITABILITY_ANALYSIS = {
    "code": "CUSTOMER_PROFITABILITY_ANALYSIS",
    "name": "Customer Profitability Analysis",
    "description": "The analysis of the profit contribution of individual customers or customer segments.",
    "formula": "Total Revenue from Customer - Total Costs Associated with Customer",
    "calculation_formula": "Total Revenue from Customer - Total Costs Associated with Customer",
    "category": "Customer Success",
    "is_active": True,
    "kpi_definition": "The analysis of the profit contribution of individual customers or customer segments.",
    "expected_business_insights": "Provides insights into the financial contribution of individual customers, guiding resource allocation and pricing strategies.",
    "measurement_approach": "Measures the profit generated by each customer, taking into account revenues and associated costs.",
    "trend_analysis": """
    * Customer profitability may show an upward trend due to increased customer retention and repeat purchases.
    * A declining trend could indicate pricing issues, increased competition, or declining customer satisfaction.
    """,
    "diagnostic_questions": """
    * What are the main drivers of profitability for our top customers?
    * Are there specific customer segments that are consistently less profitable?
    """,
    "actionable_tips": """
    * Implement customer segmentation to better understand and cater to the needs of different customer groups.
    * Regularly review pricing strategies to ensure they align with customer value and market conditions.
    * Invest in customer relationship management (CRM) systems to track and manage customer interactions and preferences.
    """,
    "visualization_suggestions": """
    * Pareto charts to identify the most profitable customers or segments.
    * Profitability trend lines over time to visualize changes in customer profitability.
    """,
    "risk_warnings": """
    * Over-reliance on a small number of highly profitable customers can pose a risk if they are lost.
    * Ignoring less profitable customer segments may lead to missed opportunities for improvement.
    """,
    "tracking_tools": """
    * Customer profitability analysis modules within ERP systems like SAP or Oracle.
    * Business intelligence tools for in-depth analysis and reporting on customer profitability.
    """,
    "integration_points": """
    * Integrate customer profitability data with sales and marketing systems to align efforts with the most profitable customers.
    * Link customer profitability analysis with customer service platforms to tailor service levels based on customer value.
    """,
    "change_impact_analysis": """
    * Improving customer profitability can lead to increased revenue and overall business growth.
    * However, changes in pricing or service levels may impact customer satisfaction and retention.
    """,
    "metadata_": {"modules": ["CUSTOMER_SUCCESS"], "source": "kpidepot.com", "import_date": "2025-11-07", "required_objects": ["Account", "Account Penetration", "Account Plan", "Account Risk", "Competitive Analysis", "Customer", "Customer Advocacy Program", "Customer Cohort", "Customer Community", "Customer Education", "Customer Feedback", "Customer Goal", "Customer Health Record", "Customer Journey", "Customer Onboarding", "Customer Segment", "Customer Success Manager", "Key Account", "Key Account Manager", "Revenue Forecast", "Sale"]},
    "modules": ["CUSTOMER_SUCCESS"],
    "module_code": "CUSTOMER_SUCCESS",
}
