"""
Gross Margin

The difference between the revenue generated by the outside sales team and the cost of goods sold.
"""

GROSS_MARGIN = {
    "code": "GROSS_MARGIN",
    "name": "Gross Margin",
    "description": "The difference between the revenue generated by the outside sales team and the cost of goods sold.",
    "formula": "(Total Sales Revenue - Cost of Goods Sold) / Total Sales Revenue * 100",
    "calculation_formula": "(Total Sales Revenue - Cost of Goods Sold) / Total Sales Revenue * 100",
    "category": "Outside Sales",
    "is_active": True,
    "full_kpi_definition": "Complete definition for Gross Margin to be added.",
    "trend_analysis": """



    * Gross margin tends to fluctuate based on changes in pricing strategies, cost of goods, and sales volume.
    * An increasing gross margin could indicate successful pricing strategies or cost control measures, while a decreasing margin may signal pricing pressure or rising costs.
    
    
    
    """,
    "diagnostic_questions": """



    * What factors are driving changes in our gross margin?
    * Are there specific products or customer segments that are impacting our overall margin?
    
    
    
    """,
    "actionable_tips": """



    * Regularly review pricing strategies and adjust based on market conditions and cost changes.
    * Analyze the cost structure to identify areas for cost reduction or efficiency improvements.
    * Provide sales teams with training on value-based selling to maintain or increase margins.
    
    
    
    """,
    "visualization_suggestions": """



    * Line charts showing gross margin trends over time.
    * Pareto charts to identify the most significant contributors to changes in gross margin.
    
    
    
    """,
    "risk_warnings": """



    * A declining gross margin may lead to reduced profitability and financial instability.
    * High gross margins without corresponding sales volume may indicate pricing strategies that are too aggressive, potentially leading to lost sales.
    
    
    
    """,
    "tracking_tools": """



    * Financial management software like QuickBooks or Xero for tracking and analyzing gross margin data.
    * Business intelligence tools such as Tableau or Power BI for in-depth analysis and visualization of gross margin trends.
    
    
    
    """,
    "integration_points": """



    * Integrate gross margin analysis with sales performance metrics to understand the relationship between sales volume and margin.
    * Link gross margin data with inventory management systems to optimize stock levels and reduce carrying costs.
    
    
    
    """,
    "change_impact_analysis": """



    * Changes in gross margin can impact overall profitability and cash flow, affecting investment decisions and financial stability.
    * Increasing gross margin may lead to higher customer acquisition costs or reduced customer satisfaction if not managed effectively.
    
    
    
    """,
    "metadata_": {"modules": ["OUTSIDE_SALES", "SALES_PERFORMANCE"], "source": "kpidepot.com", "import_date": "2025-11-07", "required_objects": ["Customer", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"], "last_validated": "2025-11-10T13:49:32.966287"},
    "required_objects": [],
    "modules": ["OUTSIDE_SALES", "SALES_PERFORMANCE"],
    "module_code": "OUTSIDE_SALES",
    "sample_data": {
        "time_series": {
                "dates": [
                        "2024-12-15",
                        "2025-01-14",
                        "2025-02-13",
                        "2025-03-15",
                        "2025-04-14",
                        "2025-05-14",
                        "2025-06-13",
                        "2025-07-13",
                        "2025-08-12",
                        "2025-09-11",
                        "2025-10-11",
                        "2025-11-10"
                ],
                "values": [
                        57.8,
                        65.5,
                        57.49,
                        58.86,
                        55.16,
                        54.62,
                        63.68,
                        65.2,
                        61.46,
                        57.33,
                        59.35,
                        54.01
                ],
                "unit": "%"
        },
        "current": {
                "value": 54.01,
                "unit": "%",
                "change": -5.34,
                "change_percent": -9.0,
                "trend": "decreasing"
        },
        "statistics": {
                "average": 59.21,
                "min": 54.01,
                "max": 65.5,
                "unit": "%"
        },
        "breakdown": [
                {
                        "category": "Direct Sales",
                        "value": 14.58,
                        "percentage": 27.0
                },
                {
                        "category": "Channel Sales",
                        "value": 12.44,
                        "percentage": 23.0
                },
                {
                        "category": "Online Sales",
                        "value": 8.88,
                        "percentage": 16.4
                },
                {
                        "category": "Enterprise Sales",
                        "value": 3.14,
                        "percentage": 5.8
                },
                {
                        "category": "Other",
                        "value": 14.97,
                        "percentage": 27.7
                }
        ],
        "metadata": {
                "generated_date": "2025-11-10T13:51:12.017952",
                "data_points": 12,
                "kpi_type": "currency",
                "kpi_name": "Gross Margin"
        }
    },
}
