"""
Lead Qualification Accuracy KPI

The accuracy with which sales development team members are able to qualify leads as sales-ready.
"""

LEAD_QUALIFICATION_ACCURACY = {
    "code": "LEAD_QUALIFICATION_ACCURACY",
    "name": "Lead Qualification Accuracy",
    "description": "The accuracy with which sales development team members are able to qualify leads as sales-ready.",
    "formula": "(Number of Correctly Qualified Leads / Total Number of Leads) * 100",
    "calculation_formula": "(Number of Correctly Qualified Leads / Total Number of Leads) * 100",
    "category": "Sales Development",
    "is_active": True,
    "kpi_definition": "The accuracy with which sales development team members are able to qualify leads as sales-ready.",
    "expected_business_insights": "Provides insights into the effectiveness of the lead qualification process and training needs of the sales team.",
    "measurement_approach": "Tracks the percentage of leads that are correctly qualified by the sales team.",
    "trend_analysis": """
    * An increasing lead qualification accuracy may indicate improved training or better alignment between marketing and sales teams.
    * A decreasing accuracy could signal changes in the target market or a need for updated qualification criteria.
    """,
    "diagnostic_questions": """
    * Are there specific criteria used for lead qualification, and are they still relevant to the current market?
    * How do the sales-ready leads identified by the sales development team compare to the actual conversion rates by the sales team?
    """,
    "actionable_tips": """
    * Regularly review and update lead qualification criteria based on feedback from the sales team and market changes.
    * Provide ongoing training and coaching to sales development team members to improve their ability to accurately qualify leads.
    * Implement lead scoring systems to objectively assess the readiness of leads for sales engagement.
    """,
    "visualization_suggestions": """
    * Line charts showing the trend in lead qualification accuracy over time.
    * Pie charts comparing the distribution of qualified and unqualified leads based on different criteria.
    """,
    "risk_warnings": """
    * Over-qualification of leads can lead to wasted sales resources and missed opportunities with truly sales-ready leads.
    * Under-qualification may result in lost sales opportunities and frustration for the sales team.
    """,
    "tracking_tools": """
    * Customer Relationship Management (CRM) systems with lead scoring capabilities to track and analyze lead qualification accuracy.
    * Sales enablement platforms that provide guidance and best practices for lead qualification.
    """,
    "integration_points": """
    * Integrate lead qualification accuracy with sales performance metrics to understand the impact of qualified leads on actual sales outcomes.
    * Link lead qualification data with marketing campaign performance to assess the quality of leads generated by different marketing efforts.
    """,
    "change_impact_analysis": """
    * Improving lead qualification accuracy can lead to more efficient use of sales resources and higher conversion rates.
    * However, overly strict qualification criteria may reduce the volume of leads, impacting overall sales pipeline and revenue potential.
    """,
    "metadata_": {"modules": ["SALES_DEVELOPMENT"], "source": "kpidepot.com", "import_date": "2025-11-07", "required_objects": ["Lead", "Lead Qualification", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"]},
    "modules": ["SALES_DEVELOPMENT"],
    "module_code": "SALES_DEVELOPMENT",
}
