"""
Lead Conversion Rate KPI

The percentage of leads generated by channel partners that convert to sales.
"""

LEAD_CONVERSION_RATE = {
    "code": "LEAD_CONVERSION_RATE",
    "name": "Lead Conversion Rate",
    "description": "The percentage of leads generated by channel partners that convert to sales.",
    "formula": "(Number of Leads Converted to Sales by Partners / Total Number of Leads Provided to Partners) * 100",
    "calculation_formula": "(Number of Leads Converted to Sales by Partners / Total Number of Leads Provided to Partners) * 100",
    "category": "Channel Sales",
    "is_active": True,
    "kpi_definition": "The percentage of leads generated by channel partners that convert to sales.",
    "expected_business_insights": "Indicates the effectiveness of channel partners in moving leads through the sales funnel to close deals.",
    "measurement_approach": "Measures the percentage of leads provided to channel partners that are converted into sales.",
    "trend_analysis": """
    * An increasing lead conversion rate may indicate improved lead quality or more effective sales strategies.
    * A decreasing rate could signal issues with lead nurturing or a decline in partner performance.
    """,
    "diagnostic_questions": """
    * Are there specific channels or partners that consistently have higher or lower lead conversion rates?
    * What are the common characteristics of leads that successfully convert versus those that do not?
    """,
    "actionable_tips": """
    * Provide targeted training and support to channel partners to improve their lead conversion skills.
    * Implement lead scoring and qualification processes to ensure higher quality leads are being pursued.
    * Regularly review and optimize the sales funnel to identify and address any bottlenecks in the conversion process.
    """,
    "visualization_suggestions": """
    * Funnel charts to visualize the progression of leads through the conversion stages.
    * Line graphs to track the lead conversion rate over time and identify any seasonal or cyclical patterns.
    """,
    "risk_warnings": """
    * A consistently low lead conversion rate can lead to wasted resources and decreased ROI from channel partner activities.
    * Rapid fluctuations in the lead conversion rate may indicate instability or inconsistency in the sales process.
    """,
    "tracking_tools": """
    * Customer Relationship Management (CRM) software to track and analyze lead interactions and conversions.
    * Marketing automation platforms to streamline lead nurturing and follow-up processes.
    """,
    "integration_points": """
    * Integrate lead conversion rate data with marketing analytics to understand the effectiveness of lead generation efforts.
    * Link lead conversion rate with sales performance metrics to identify areas for improvement in the overall sales process.
    """,
    "change_impact_analysis": """
    * Improving the lead conversion rate can lead to increased revenue and a more efficient use of sales and marketing resources.
    * However, a focus solely on increasing conversion rates may lead to neglecting lead quality and long-term customer satisfaction.
    """,
    "metadata_": {"modules": ["CHANNEL_SALES", "SALES_OPERATIONS", "SALES_PERFORMANCE"], "source": "kpidepot.com", "import_date": "2025-11-07", "required_objects": ["Channel Conflict", "Channel Deal", "Channel Market", "Channel Partner", "Lead", "Lead Qualification", "Opportunity", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"]},
    "modules": ["CHANNEL_SALES", "SALES_OPERATIONS", "SALES_PERFORMANCE"],
    "module_code": "CHANNEL_SALES",
}
