"""
Partner Pipeline Contribution

The amount of potential sales revenue present in the sales pipeline due to channel partners, indicating their contribution to future sales.
"""

PARTNER_PIPELINE_CONTRIBUTION = {
    "code": "PARTNER_PIPELINE_CONTRIBUTION",
    "name": "Partner Pipeline Contribution",
    "description": "The amount of potential sales revenue present in the sales pipeline due to channel partners, indicating their contribution to future sales.",
    "formula": "Total Value of Sales Pipeline Generated by Partners",
    "calculation_formula": "Total Value of Sales Pipeline Generated by Partners",
    "category": "Channel Sales",
    "is_active": True,
    "full_kpi_definition": "Complete definition for Partner Pipeline Contribution to be added.",
    "trend_analysis": """



    * Increasing partner pipeline contribution may indicate successful partner enablement and engagement.
    * Decreasing contribution could signal issues with partner relationships or lack of focus on channel sales.
    
    
    
    """,
    "diagnostic_questions": """



    * Are there specific partners consistently contributing to the pipeline, and if not, why?
    * How does the partner pipeline contribution compare to direct sales pipeline contribution?
    
    
    
    """,
    "actionable_tips": """



    * Invest in partner training and enablement to improve their ability to generate and manage pipeline opportunities.
    * Implement a lead distribution and tracking system to ensure partners are effectively managing their pipeline contributions.
    
    
    
    """,
    "visualization_suggestions": """



    * Stacked bar charts comparing partner and direct sales pipeline contributions over time.
    * Line graphs showing the trend of partner pipeline contribution as a percentage of total sales pipeline.
    
    
    
    """,
    "risk_warnings": """



    * Over-reliance on a few partners for pipeline contribution can create vulnerability if those relationships sour.
    * Low partner pipeline contribution may indicate a need for reevaluation of the partner program or strategy.
    
    
    
    """,
    "tracking_tools": """



    * Customer Relationship Management (CRM) systems with partner management capabilities to track partner pipeline contributions.
    * Partner Relationship Management (PRM) platforms to provide partners with tools for managing their pipeline contributions.
    
    
    
    """,
    "integration_points": """



    * Integrate partner pipeline contribution data with sales forecasting to better predict future revenue from channel sales.
    * Link partner pipeline contribution with incentive and commission systems to ensure partners are appropriately rewarded for their contributions.
    
    
    
    """,
    "change_impact_analysis": """



    * Increasing partner pipeline contribution can lead to higher overall sales revenue and market reach.
    * However, a decrease in partner pipeline contribution may require a shift in resources towards direct sales efforts.
    
    
    
    """,
    "metadata_": {"modules": ["CHANNEL_SALES"], "source": "kpidepot.com", "import_date": "2025-11-07", "required_objects": ["Channel Conflict", "Channel Deal", "Channel Market", "Channel Partner", "Customer", "Partner Agreement", "Partner Incentive", "Partner Performance Scorecard", "Partner Portal", "Partner Training", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Pipeline", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"], "last_validated": "2025-11-10T13:49:33.206437"},
    "required_objects": [],
    "modules": ["CHANNEL_SALES"],
    "module_code": "CHANNEL_SALES",
    "sample_data": {
        "time_series": {
                "dates": [
                        "2024-12-15",
                        "2025-01-14",
                        "2025-02-13",
                        "2025-03-15",
                        "2025-04-14",
                        "2025-05-14",
                        "2025-06-13",
                        "2025-07-13",
                        "2025-08-12",
                        "2025-09-11",
                        "2025-10-11",
                        "2025-11-10"
                ],
                "values": [
                        578.91,
                        561.99,
                        527.14,
                        596.55,
                        486.26,
                        487.39,
                        524.22,
                        513.42,
                        486.86,
                        552.02,
                        559.63,
                        623.14
                ],
                "unit": "units"
        },
        "current": {
                "value": 623.14,
                "unit": "units",
                "change": 63.51,
                "change_percent": 11.3,
                "trend": "stable"
        },
        "statistics": {
                "average": 541.46,
                "min": 486.26,
                "max": 623.14,
                "unit": "units"
        },
        "breakdown": [
                {
                        "category": "Direct Sales",
                        "value": 104.18,
                        "percentage": 16.7
                },
                {
                        "category": "Channel Sales",
                        "value": 169.93,
                        "percentage": 27.3
                },
                {
                        "category": "Online Sales",
                        "value": 120.18,
                        "percentage": 19.3
                },
                {
                        "category": "Enterprise Sales",
                        "value": 64.53,
                        "percentage": 10.4
                },
                {
                        "category": "Other",
                        "value": 164.32,
                        "percentage": 26.4
                }
        ],
        "metadata": {
                "generated_date": "2025-11-10T13:51:12.493477",
                "data_points": 12,
                "kpi_type": "metric",
                "kpi_name": "Partner Pipeline Contribution"
        }
    },
}
