"""
Recurring Revenue (MRR)

The amount of recurring revenue generated by the sales team each period.
"""

RECURRING_REVENUE_MRR = {
    "code": "RECURRING_REVENUE_MRR",
    "name": "Recurring Revenue (MRR)",
    "description": "The amount of recurring revenue generated by the sales team each period.",
    "formula": "Sum of All Recurring Revenue for the period",
    "calculation_formula": "Sum of All Recurring Revenue for the period",
    "category": "Inside Sales",
    "is_active": True,
    "full_kpi_definition": "Complete definition for Recurring Revenue (MRR) to be added.",
    "trend_analysis": """



    * Increasing MRR over time may indicate successful upselling or cross-selling strategies.
    * Decreasing MRR could signal customer churn or ineffective retention efforts.
    
    
    
    """,
    "diagnostic_questions": """



    * Are there specific customer segments or products that contribute significantly to MRR?
    * How does our MRR compare to industry benchmarks or competitors?
    
    
    
    """,
    "actionable_tips": """



    * Implement customer success programs to increase retention and expand customer lifetime value.
    * Regularly review pricing strategies to ensure they align with customer value and market demand.
    * Invest in sales training to improve upselling and cross-selling techniques.
    
    
    
    """,
    "visualization_suggestions": """



    * Line charts showing MRR trends over time.
    * Pie charts to visualize the contribution of different customer segments or products to MRR.
    
    
    
    """,
    "risk_warnings": """



    * Dependence on a small number of high-value customers may pose a risk if they churn.
    * Fluctuations in MRR could indicate market volatility or competitive pressures.
    
    
    
    """,
    "tracking_tools": """



    * Customer relationship management (CRM) software to track customer interactions and identify upsell opportunities.
    * Subscription management platforms to streamline recurring billing and subscription management processes.
    
    
    
    """,
    "integration_points": """



    * Integrate MRR tracking with marketing automation systems to align sales and marketing efforts for customer retention and expansion.
    * Link MRR data with financial systems for accurate revenue forecasting and reporting.
    
    
    
    """,
    "change_impact_analysis": """



    * Increasing MRR can positively impact overall revenue and profitability.
    * However, aggressive upselling strategies may lead to customer dissatisfaction and increased churn.
    
    
    
    """,
    "metadata_": {"modules": ["INSIDE_SALES", "OUTSIDE_SALES", "SALES_OPERATIONS"], "source": "kpidepot.com", "import_date": "2025-11-07", "required_objects": ["Customer", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"], "last_validated": "2025-11-10T13:49:33.320044"},
    "required_objects": [],
    "modules": ["INSIDE_SALES", "OUTSIDE_SALES", "SALES_OPERATIONS"],
    "module_code": "INSIDE_SALES",
    "sample_data": {
        "time_series": {
                "dates": [
                        "2024-12-15",
                        "2025-01-14",
                        "2025-02-13",
                        "2025-03-15",
                        "2025-04-14",
                        "2025-05-14",
                        "2025-06-13",
                        "2025-07-13",
                        "2025-08-12",
                        "2025-09-11",
                        "2025-10-11",
                        "2025-11-10"
                ],
                "values": [
                        88296.52,
                        89011.07,
                        94158.26,
                        89890.83,
                        82760.77,
                        85944.33,
                        93283.98,
                        93522.66,
                        85015.9,
                        94060.17,
                        92139.49,
                        88537.32
                ],
                "unit": "$"
        },
        "current": {
                "value": 88537.32,
                "unit": "$",
                "change": -3602.17,
                "change_percent": -3.9,
                "trend": "stable"
        },
        "statistics": {
                "average": 89718.44,
                "min": 82760.77,
                "max": 94158.26,
                "unit": "$"
        },
        "breakdown": [
                {
                        "category": "Direct Sales",
                        "value": 20234.62,
                        "percentage": 22.9
                },
                {
                        "category": "Channel Sales",
                        "value": 10568.95,
                        "percentage": 11.9
                },
                {
                        "category": "Online Sales",
                        "value": 10629.99,
                        "percentage": 12.0
                },
                {
                        "category": "Enterprise Sales",
                        "value": 7027.85,
                        "percentage": 7.9
                },
                {
                        "category": "Other",
                        "value": 40075.91,
                        "percentage": 45.3
                }
        ],
        "metadata": {
                "generated_date": "2025-11-10T13:51:12.754193",
                "data_points": 12,
                "kpi_type": "currency",
                "kpi_name": "Recurring Revenue (MRR)"
        }
    },
}
