from analytics_models.definitions.kpis.base_kpi import BaseKPI

class ReturnOnSalesInvestmentRosi(BaseKPI):
    def __init__(self):
        super().__init__(
            code="RETURN_ON_SALES_INVESTMENT_ROSI",
            name_="Return on Sales Investment (ROSI)",
            description_="A metric that measures the profit generated by investments in the sales process, reflecting the efficiency and effectiveness of sales activities.",
            category_="Business Development",
            modules_=["BUSINESS_DEVELOPMENT"],
            required_objects=['Return'],
            formula_="(Gross Profit from Sales - Sales Investment) / Sales Investment",
            aggregation_methods=['average'],
            time_periods=['daily', 'weekly', 'monthly', 'quarterly', 'annually']
        )
