"""
Revenue per Sales Representative

The amount of revenue generated by each sales representative, indicating their individual productivity and contribution to the team.
"""

REVENUE_PER_SALES_REPRESENTATIVE = {
    "code": "REVENUE_PER_SALES_REPRESENTATIVE",
    "name": "Revenue per Sales Representative",
    "description": "The amount of revenue generated by each sales representative, indicating their individual productivity and contribution to the team.",
    "formula": "Total Revenue / Number of Sales Representatives",
    "calculation_formula": "To be defined",
    "category": "Business Development",
    "is_active": True,
    "full_kpi_definition": "Complete definition for Revenue per Sales Representative to be added.",
    "trend_analysis": "Trend analysis to be defined.",
    "diagnostic_questions": """


* What factors are influencing this metric?
* Are there any anomalies in the data?
    
    
    """,
    "actionable_tips": """


* Monitor this KPI regularly
* Set appropriate targets and thresholds
    
    
    """,
    "visualization_suggestions": """


* Line chart for time series analysis
* Bar chart for comparisons
    
    
    """,
    "risk_warnings": "* Monitor for significant deviations from expected values",
    "tracking_tools": "* CRM or analytics platform",
    "integration_points": "* Integrate with related business metrics",
    "change_impact_analysis": "Changes in this KPI may impact related business processes.",
    "metadata_": {"modules": ["BUSINESS_DEVELOPMENT"], "required_objects": ["Product"], "last_validated": "2025-11-10T13:49:33.360924"},
    "required_objects": [],
    "modules": ["BUSINESS_DEVELOPMENT"],
    "module_code": "BUSINESS_DEVELOPMENT",
    "sample_data": {
        "time_series": {
                "dates": [
                        "2024-12-15",
                        "2025-01-14",
                        "2025-02-13",
                        "2025-03-15",
                        "2025-04-14",
                        "2025-05-14",
                        "2025-06-13",
                        "2025-07-13",
                        "2025-08-12",
                        "2025-09-11",
                        "2025-10-11",
                        "2025-11-10"
                ],
                "values": [
                        89,
                        72,
                        52,
                        53,
                        52,
                        97,
                        60,
                        98,
                        52,
                        76,
                        77,
                        70
                ],
                "unit": "count"
        },
        "current": {
                "value": 70,
                "unit": "count",
                "change": -7,
                "change_percent": -9.1,
                "trend": "stable"
        },
        "statistics": {
                "average": 70.67,
                "min": 52,
                "max": 98,
                "unit": "count"
        },
        "breakdown": [
                {
                        "category": "Direct Sales",
                        "value": 20.3,
                        "percentage": 29.0
                },
                {
                        "category": "Channel Sales",
                        "value": 8.05,
                        "percentage": 11.5
                },
                {
                        "category": "Online Sales",
                        "value": 7.15,
                        "percentage": 10.2
                },
                {
                        "category": "Enterprise Sales",
                        "value": 6.14,
                        "percentage": 8.8
                },
                {
                        "category": "Other",
                        "value": 28.36,
                        "percentage": 40.5
                }
        ],
        "metadata": {
                "generated_date": "2025-11-10T13:51:12.838110",
                "data_points": 12,
                "kpi_type": "count",
                "kpi_name": "Revenue per Sales Representative"
        }
    },
}
