from analytics_models.definitions.kpis.base_kpi import BaseKPI

class RevenuePerSalesRepresentative(BaseKPI):
    def __init__(self):
        super().__init__(
            code="REVENUE_PER_SALES_REPRESENTATIVE",
            name_="Revenue per Sales Representative",
            description_="The amount of revenue generated by each sales representative, indicating their individual productivity and contribution to the team.",
            category_="Business Development",
            modules_=["BUSINESS_DEVELOPMENT"],
            required_objects=['Product'],
            formula_="Total Revenue / Number of Sales Representatives",
            aggregation_methods=['sum', 'count'],
            time_periods=['daily', 'weekly', 'monthly', 'quarterly', 'annually']
        )
