"""
Revenue Growth KPI

The percentage increase in revenue generated by channel partners over a given period.
"""

from analytics_models import KPI

REVENUE_GROWTH = KPI(
    name="Revenue Growth",
    code="REVENUE_GROWTH",
    category="Channel Sales",
    
    # Core Definition
    description="The percentage increase in revenue generated by channel partners over a given period.",
    kpi_definition="The percentage increase in revenue generated by channel partners over a given period.",
    expected_business_insights="Indicates the overall financial health and business growth, which can include both direct and channel sales.",
    measurement_approach="Measures the percentage increase in total revenue over a specific time period.",
    
    # Formula
    formula="((Current Period Total Revenue - Previous Period Total Revenue) / Previous Period Total Revenue) * 100",
    calculation_formula="((Current Period Total Revenue - Previous Period Total Revenue) / Previous Period Total Revenue) * 100",
    
    # Analysis
    trend_analysis="""
    * Increasing revenue growth may indicate successful channel partner engagement and expansion of market reach.
    * Decreasing growth could signal market saturation or declining partner performance.
    """,
    diagnostic_questions="""
    * What specific strategies or initiatives have contributed to the recent revenue growth?
    * Are there any external factors, such as changes in the market or competitive landscape, that could explain the trend in revenue growth?
    """,
    
    # Action & Visualization
    actionable_tips="""
    * Provide additional sales training and support to channel partners to enhance their effectiveness.
    * Explore new market segments or geographical areas to further expand revenue opportunities.
    * Regularly review and optimize the channel partner incentive and commission structures to ensure alignment with revenue growth objectives.
    """,
    visualization_suggestions="""
    * Line charts showing revenue growth over time, segmented by channel partner or product category.
    * Pie charts illustrating the contribution of different channel partners to overall revenue growth.
    """,
    
    # Risk & Integration
    risk_warnings="""
    * Rapid revenue growth may strain operational resources and lead to fulfillment challenges.
    * Dependence on a small number of high-performing channel partners can create vulnerability to market fluctuations or partner disengagement.
    """,
    tracking_tools="""
    * Customer Relationship Management (CRM) systems to track and manage interactions with channel partners and monitor sales performance.
    * Business Intelligence (BI) tools for in-depth analysis of revenue growth patterns and partner contribution.
    """,
    integration_points="""
    * Integrate revenue growth data with financial systems to assess the impact on overall company performance and profitability.
    * Link revenue growth metrics with marketing and product development efforts to align strategies and resources for sustained growth.
    """,
    change_impact_analysis="""
    * Increasing revenue growth may require adjustments in production, inventory, and distribution to meet higher demand levels.
    * Conversely, declining revenue growth may necessitate cost-cutting measures or strategic realignment to maintain profitability.
    """,
    
    is_active=True,
    metadata_={
        "modules": ["CHANNEL_SALES", "SALES_PERFORMANCE"],
        "source": "kpidepot.com",
        "import_date": "2025-11-07"
        "replaces": ["REVENUE_GROWTH_RATE"],
        "required_objects": ["Channel Conflict", "Channel Deal", "Channel Market", "Channel Partner", "Customer", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"]
    }
)
