from analytics_models.definitions.kpis.base_kpi import BaseKPI

class SalesGrowth(BaseKPI):
    def __init__(self):
        super().__init__(
            code="SALES_GROWTH",
            name_="Sales Growth",
            description_="The percentage of revenue growth generated by the Business Development Team.",
            category_="Business Development",
            modules_=["BUSINESS_DEVELOPMENT"],
            required_objects=[],
            formula_="((Current Period Sales - Previous Period Sales) / Previous Period Sales) * 100",
            aggregation_methods=['average'],
            time_periods=['daily', 'weekly', 'monthly', 'quarterly', 'annually']
        )
