"""
Sales by Channel

The amount of sales generated by each sales channel (e.g., online, retail, direct sales).
"""

SALES_BY_CHANNEL = {
    "code": "SALES_BY_CHANNEL",
    "name": "Sales by Channel",
    "description": "The amount of sales generated by each sales channel (e.g., online, retail, direct sales).",
    "formula": "Revenue attributed to each sales channel",
    "calculation_formula": "Revenue attributed to each sales channel",
    "category": "Sales Operations",
    "is_active": True,
    "full_kpi_definition": "Complete definition for Sales by Channel to be added.",
    "trend_analysis": """



    * Online sales may show a consistent upward trend, indicating the growing importance of e-commerce channels.
    * Direct sales might exhibit a declining trend, signaling a need for reevaluation of sales strategies or customer engagement approaches.
    
    
    
    """,
    "diagnostic_questions": """



    * Are there specific products that perform better in certain sales channels?
    * How do customer demographics and preferences align with the performance of each sales channel?
    
    
    
    """,
    "actionable_tips": """



    * Invest in targeted marketing and promotions for underperforming sales channels.
    * Optimize online sales platforms for a seamless customer experience.
    * Provide additional training and resources for direct sales teams to improve performance.
    
    
    
    """,
    "visualization_suggestions": """



    * Stacked bar charts to compare sales performance across different channels over time.
    * Line graphs to track the growth or decline of each sales channel individually.
    
    
    
    """,
    "risk_warnings": """



    * Relying too heavily on a single sales channel can expose the business to significant risk if that channel underperforms or faces disruptions.
    * Ignoring the performance of certain sales channels may lead to missed opportunities and revenue loss.
    
    
    
    """,
    "tracking_tools": """



    * Customer relationship management (CRM) software to track customer interactions and preferences across different sales channels.
    * Data analytics tools to analyze sales data and identify patterns or trends in each channel.
    
    
    
    """,
    "integration_points": """



    * Integrate sales channel performance data with inventory management systems to ensure adequate stock levels for each channel.
    * Link sales channel data with customer support systems to provide consistent and personalized service across all channels.
    
    
    
    """,
    "change_impact_analysis": """



    * Improving the performance of underperforming sales channels can lead to increased revenue and market share.
    * Shifting focus away from a historically strong sales channel may initially impact overall sales volume but could lead to long-term diversification and resilience.
    
    
    
    """,
    "metadata_": {"modules": ["SALES_OPERATIONS"], "source": "kpidepot.com", "import_date": "2025-11-07", "required_objects": ["Channel Conflict", "Channel Deal", "Channel Market", "Channel Partner", "Customer", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"], "last_validated": "2025-11-10T13:49:33.371493"},
    "required_objects": [],
    "modules": ["SALES_OPERATIONS"],
    "module_code": "SALES_OPERATIONS",
    "sample_data": {
        "time_series": {
                "dates": [
                        "2024-12-15",
                        "2025-01-14",
                        "2025-02-13",
                        "2025-03-15",
                        "2025-04-14",
                        "2025-05-14",
                        "2025-06-13",
                        "2025-07-13",
                        "2025-08-12",
                        "2025-09-11",
                        "2025-10-11",
                        "2025-11-10"
                ],
                "values": [
                        358.57,
                        468.84,
                        331.25,
                        417.98,
                        354.37,
                        374.63,
                        450.14,
                        437.71,
                        423.97,
                        389.39,
                        430.76,
                        455.55
                ],
                "unit": "units"
        },
        "current": {
                "value": 455.55,
                "unit": "units",
                "change": 24.79,
                "change_percent": 5.8,
                "trend": "increasing"
        },
        "statistics": {
                "average": 407.76,
                "min": 331.25,
                "max": 468.84,
                "unit": "units"
        },
        "breakdown": [
                {
                        "category": "Direct Sales",
                        "value": 116.23,
                        "percentage": 25.5
                },
                {
                        "category": "Channel Sales",
                        "value": 78.12,
                        "percentage": 17.1
                },
                {
                        "category": "Online Sales",
                        "value": 41.24,
                        "percentage": 9.1
                },
                {
                        "category": "Enterprise Sales",
                        "value": 45.31,
                        "percentage": 9.9
                },
                {
                        "category": "Other",
                        "value": 174.65,
                        "percentage": 38.3
                }
        ],
        "metadata": {
                "generated_date": "2025-11-10T13:51:12.860971",
                "data_points": 12,
                "kpi_type": "metric",
                "kpi_name": "Sales by Channel"
        }
    },
}
