"""
Sales Rep Productivity

The average revenue generated by each sales rep. A higher revenue per rep indicates effective training and coaching.
"""

SALES_REP_PRODUCTIVITY = {
    "code": "SALES_REP_PRODUCTIVITY",
    "name": "Sales Rep Productivity",
    "description": "The average revenue generated by each sales rep. A higher revenue per rep indicates effective training and coaching.",
    "formula": "Total Sales or Revenue Generated / Number of Sales Reps",
    "calculation_formula": "Total Sales or Revenue Generated / Number of Sales Reps",
    "category": "Sales Training and Coaching",
    "is_active": True,
    "full_kpi_definition": "Complete definition for Sales Rep Productivity to be added.",
    "trend_analysis": """



    * An increasing sales rep productivity may indicate effective training and coaching methods, leading to improved performance.
    * A decreasing productivity could signal issues with training, coaching, or changes in the market that need to be addressed.
    
    
    
    """,
    "diagnostic_questions": """



    * Are there specific sales techniques or strategies that have been particularly effective in driving higher productivity?
    * How does the productivity of top-performing sales reps compare to the average, and what can be learned from their methods?
    
    
    
    """,
    "actionable_tips": """



    * Regularly review and update training materials to ensure they are relevant and effective.
    * Provide ongoing coaching and feedback to sales reps to help them continuously improve their skills and performance.
    * Implement a mentorship program where top-performing sales reps can share their knowledge and best practices with others.
    
    
    
    """,
    "visualization_suggestions": """



    * Line charts showing the productivity of each sales rep over time to identify trends and outliers.
    * Comparison bar charts to visualize the differences in productivity between different teams or regions.
    
    
    
    """,
    "risk_warnings": """



    * Low sales rep productivity can lead to missed revenue targets and decreased overall sales performance.
    * High productivity without proper training and coaching may result in burnout and decreased job satisfaction among sales reps.
    
    
    
    """,
    "tracking_tools": """



    * Sales performance management software to track and analyze individual sales rep productivity and identify areas for improvement.
    * Learning management systems to deliver and track the effectiveness of training materials and courses.
    
    
    
    """,
    "integration_points": """



    * Integrate sales rep productivity data with customer relationship management (CRM) systems to understand the relationship between productivity and customer interactions.
    * Link productivity metrics with sales incentive programs to align performance goals with compensation.
    
    
    
    """,
    "change_impact_analysis": """



    * Improving sales rep productivity can lead to increased revenue and customer satisfaction, but may also require additional resources for training and coaching.
    * Decreasing productivity may indicate the need for changes in training and coaching methods, which could impact the overall sales strategy and performance.
    
    
    
    """,
    "metadata_": {"modules": ["SALES_TRAINING_COACHING"], "source": "kpidepot.com", "import_date": "2025-11-07", "required_objects": ["Coaching Session", "Customer", "Partner Training", "Product", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program", "Training Program"], "last_validated": "2025-11-10T13:49:33.484956"},
    "required_objects": [],
    "modules": ["SALES_TRAINING_COACHING"],
    "module_code": "SALES_TRAINING_COACHING",
    "sample_data": {
        "time_series": {
                "dates": [
                        "2024-12-15",
                        "2025-01-14",
                        "2025-02-13",
                        "2025-03-15",
                        "2025-04-14",
                        "2025-05-14",
                        "2025-06-13",
                        "2025-07-13",
                        "2025-08-12",
                        "2025-09-11",
                        "2025-10-11",
                        "2025-11-10"
                ],
                "values": [
                        398,
                        386,
                        383,
                        388,
                        364,
                        368,
                        410,
                        406,
                        365,
                        401,
                        393,
                        368
                ],
                "unit": "count"
        },
        "current": {
                "value": 368,
                "unit": "count",
                "change": -25,
                "change_percent": -6.4,
                "trend": "stable"
        },
        "statistics": {
                "average": 385.83,
                "min": 364,
                "max": 410,
                "unit": "count"
        },
        "breakdown": [
                {
                        "category": "Product Line A",
                        "value": 109.79,
                        "percentage": 29.8
                },
                {
                        "category": "Product Line B",
                        "value": 88.84,
                        "percentage": 24.1
                },
                {
                        "category": "Product Line C",
                        "value": 45.41,
                        "percentage": 12.3
                },
                {
                        "category": "Services",
                        "value": 30.9,
                        "percentage": 8.4
                },
                {
                        "category": "Other",
                        "value": 93.06,
                        "percentage": 25.3
                }
        ],
        "metadata": {
                "generated_date": "2025-11-10T13:51:13.161538",
                "data_points": 12,
                "kpi_type": "count",
                "kpi_name": "Sales Rep Productivity"
        }
    },
}
