"""
Sales per Rep KPI

The average sales revenue generated by each sales representative.
"""

SALES_PER_REP = {
    "code": "SALES_PER_REP",
    "name": "Sales per Rep",
    "description": "The average sales revenue generated by each sales representative.",
    "formula": "Total Sales Revenue / Number of Sales Representatives",
    "calculation_formula": "Total Sales Revenue / Number of Sales Representatives",
    "category": "Outside Sales",
    "is_active": True,
    "kpi_definition": "The average sales revenue generated by each sales representative.",
    "expected_business_insights": "Indicates individual sales performance and can guide decisions on training, incentives, and resource allocation.",
    "measurement_approach": "Calculates the average amount of sales generated by each sales representative.",
    "trend_analysis": """
    * Sales per rep may increase over time as reps gain experience and build stronger relationships with clients.
    * A decreasing trend could indicate market saturation or increased competition affecting individual rep performance.
    """,
    "diagnostic_questions": """
    * Are there specific territories or product lines where certain reps consistently outperform others?
    * How does the average sales per rep compare to industry benchmarks or historical company data?
    """,
    "actionable_tips": """
    * Provide ongoing training and support to help reps improve their sales techniques and customer relationship management.
    * Consider restructuring territories or accounts to better align with individual rep strengths and market opportunities.
    * Implement a mentorship program where experienced reps can share their knowledge and best practices with newer team members.
    """,
    "visualization_suggestions": """
    * Line charts showing the sales per rep over time to identify trends and patterns.
    * Comparison bar charts to visualize the performance of different reps or territories.
    """,
    "risk_warnings": """
    * Low sales per rep may indicate underperforming reps or ineffective sales strategies that could impact overall revenue.
    * High sales per rep may lead to burnout or over-reliance on individual reps, posing a risk to long-term sales sustainability.
    """,
    "tracking_tools": """
    * Customer relationship management (CRM) software to track individual rep performance and customer interactions.
    * Sales analytics tools to identify patterns and opportunities for improvement in sales performance.
    """,
    "integration_points": """
    * Integrate sales per rep data with compensation and incentive programs to align rewards with performance.
    * Link sales per rep with customer feedback and satisfaction metrics to understand the impact of individual reps on customer relationships.
    """,
    "change_impact_analysis": """
    * Improving sales per rep can lead to increased revenue and customer satisfaction, but may also require additional resources for training and support.
    * Conversely, a decline in sales per rep could signal the need for strategic changes in sales management and resource allocation.
    """,
    "metadata_": {"modules": ["OUTSIDE_SALES"], "source": "kpidepot.com", "import_date": "2025-11-07", "required_objects": ["Customer", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"]},
    "modules": ["OUTSIDE_SALES"],
    "module_code": "OUTSIDE_SALES",
}
