"""
Sales Revenue KPI

The total revenue generated by the inside sales team during a specific time period. It helps track the team's overall performance and success in meeting sales goals.
"""

SALES_REVENUE = {
    "code": "SALES_REVENUE",
    "name": "Sales Revenue",
    "description": "The total revenue generated by the inside sales team during a specific time period. It helps track the team's overall performance and success in meeting sales goals.",
    "formula": "Sum of All Sales Income",
    "calculation_formula": "Sum of All Sales Income",
    "category": "Inside Sales",
    "is_active": True,
    "kpi_definition": "The total revenue generated by the inside sales team during a specific time period. It helps track the team's overall performance and success in meeting sales goals.",
    "expected_business_insights": "Provides the most direct measure of the success of sales activities and business growth.",
    "measurement_approach": "Total income from sales of goods or services.",
    "trend_analysis": """
    * Increasing sales revenue over time may indicate successful product launches or effective sales strategies.
    * Decreasing revenue could signal market saturation, increased competition, or changes in customer preferences.
    """,
    "diagnostic_questions": """
    * What are the main drivers of the changes in sales revenue?
    * Are there specific customer segments or regions that are contributing more to the revenue?
    """,
    "actionable_tips": """
    * Implement targeted marketing campaigns to reach new customer segments or regions.
    * Provide additional sales training and support to the inside sales team to improve their performance.
    * Regularly review and update the product portfolio to ensure it meets current market demands.
    """,
    "visualization_suggestions": """
    * Line charts showing revenue trends over time.
    * Pie charts to illustrate revenue contribution by different customer segments or product categories.
    """,
    "risk_warnings": """
    * Declining sales revenue may lead to financial instability and decreased resources for business operations.
    * Relying too heavily on a few key customers for a large portion of revenue can pose a risk if those customers reduce their spending.
    """,
    "tracking_tools": """
    * Customer relationship management (CRM) software to track customer interactions and identify potential sales opportunities.
    * Business intelligence tools to analyze sales data and identify trends or opportunities for improvement.
    """,
    "integration_points": """
    * Integrate sales revenue data with marketing and customer service systems to gain a comprehensive view of customer interactions and behaviors.
    * Link sales revenue with financial systems to track the impact on overall business performance and profitability.
    """,
    "change_impact_analysis": """
    * Increasing sales revenue may lead to higher profitability and business growth, but it could also strain operational resources if not managed effectively.
    * Decreasing revenue may require cost-cutting measures or strategic shifts to maintain business stability and competitiveness.
    """,
    "metadata_": {"modules": ["INSIDE_SALES"], "source": "kpidepot.com", "import_date": "2025-11-07", "required_objects": ["Customer", "Deal", "Goal", "Lead", "Meeting", "Opportunity", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"]},
    "modules": ["INSIDE_SALES"],
    "module_code": "INSIDE_SALES",
}
