"""
Sales Growth

The percentage of revenue growth generated by the Business Development Team.
"""

SALES_GROWTH = {
    "code": "SALES_GROWTH",
    "name": "Sales Growth",
    "description": "The percentage of revenue growth generated by the Business Development Team.",
    "formula": "((Current Period Sales - Previous Period Sales) / Previous Period Sales) * 100",
    "calculation_formula": "((Current Period Sales - Previous Period Sales) / Previous Period Sales) * 100",
    "category": "Business Development",
    "is_active": True,
    "full_kpi_definition": "Complete definition for Sales Growth to be added.",
    "trend_analysis": "Trend analysis to be defined.",
    "diagnostic_questions": """



* What factors are influencing this metric?
* Are there any anomalies in the data?
    
    
    
    """,
    "actionable_tips": """



* Monitor this KPI regularly
* Set appropriate targets and thresholds
    
    
    
    """,
    "visualization_suggestions": """



* Line chart for time series analysis
* Bar chart for comparisons
    
    
    
    """,
    "risk_warnings": "* Monitor for significant deviations from expected values",
    "tracking_tools": "* CRM or analytics platform",
    "integration_points": "* Integrate with related business metrics",
    "change_impact_analysis": "Changes in this KPI may impact related business processes.",
    "metadata_": {"modules": ["BUSINESS_DEVELOPMENT"], "required_objects": [], "last_validated": "2025-11-10T13:49:33.430449"},
    "required_objects": [],
    "modules": ["BUSINESS_DEVELOPMENT"],
    "module_code": "BUSINESS_DEVELOPMENT",
    "sample_data": {
        "time_series": {
                "dates": [
                        "2024-12-15",
                        "2025-01-14",
                        "2025-02-13",
                        "2025-03-15",
                        "2025-04-14",
                        "2025-05-14",
                        "2025-06-13",
                        "2025-07-13",
                        "2025-08-12",
                        "2025-09-11",
                        "2025-10-11",
                        "2025-11-10"
                ],
                "values": [
                        48.04,
                        60.45,
                        50.93,
                        55.77,
                        62.68,
                        60.19,
                        49.02,
                        63.38,
                        62.53,
                        63.68,
                        50.19,
                        47.73
                ],
                "unit": "%"
        },
        "current": {
                "value": 47.73,
                "unit": "%",
                "change": -2.46,
                "change_percent": -4.9,
                "trend": "stable"
        },
        "statistics": {
                "average": 56.22,
                "min": 47.73,
                "max": 63.68,
                "unit": "%"
        },
        "breakdown": [
                {
                        "category": "Direct Sales",
                        "value": 14.5,
                        "percentage": 30.4
                },
                {
                        "category": "Channel Sales",
                        "value": 9.78,
                        "percentage": 20.5
                },
                {
                        "category": "Online Sales",
                        "value": 5.07,
                        "percentage": 10.6
                },
                {
                        "category": "Enterprise Sales",
                        "value": 4.59,
                        "percentage": 9.6
                },
                {
                        "category": "Other",
                        "value": 13.79,
                        "percentage": 28.9
                }
        ],
        "metadata": {
                "generated_date": "2025-11-10T13:51:13.006154",
                "data_points": 12,
                "kpi_type": "metric",
                "kpi_name": "Sales Growth"
        }
    },
}
