import sys; from pathlib import Path; sys.path.insert(0, str(Path(__file__).parent)); from base_kpi import BaseKPI

class SupplyChainReturnOnInvestmentRoi(BaseKPI):
    def __init__(self):
        super().__init__(
            code="SUPPLY_CHAIN_RETURN_ON_INVESTMENT_ROI",
            name_="Supply Chain Return on Investment (ROI)",
            description_="The financial return generated by supply chain investments, calculating the benefits relative to the costs involved.",
            category_="Iso 22004",
            modules_=["ISO_22004"],
            required_objects=['Return'],
            formula_="(Gain from Supply Chain Investment - Cost of Supply Chain Investment) / Cost of Supply Chain Investment",
            aggregation_methods=['average'],
            time_periods=['daily', 'weekly', 'monthly', 'quarterly', 'annually']
        )
