"""
Time to Close from First Contact KPI

The average time it takes to close a sale from the first point of contact with a lead.
"""

TIME_TO_CLOSE_FROM_FIRST_CONTACT = {
    "code": "TIME_TO_CLOSE_FROM_FIRST_CONTACT",
    "name": "Time to Close from First Contact",
    "description": "The average time it takes to close a sale from the first point of contact with a lead.",
    "formula": "(Date of Sale Closure - Date of First Contact)",
    "calculation_formula": "(Date of Sale Closure - Date of First Contact)",
    "category": "Outside Sales",
    "is_active": True,
    "kpi_definition": "The average time it takes to close a sale from the first point of contact with a lead.",
    "expected_business_insights": "Enables analysis of sales cycle efficiency and can drive strategies for reducing the sales timeline.",
    "measurement_approach": "Captures the duration from the initial contact with a prospective customer to the moment the sale is closed.",
    "trend_analysis": """
    * Shortening time to close may indicate improved lead qualification or more effective sales strategies.
    * An increasing time to close could signal increased competition or a need for sales process optimization.
    """,
    "diagnostic_questions": """
    * Are there specific stages in the sales process where leads tend to stall?
    * How does our average time to close compare with industry benchmarks or with different lead sources?
    """,
    "actionable_tips": """
    * Implement lead scoring to prioritize high-quality leads and focus efforts on those most likely to convert.
    * Provide additional sales training or resources to address common objections or roadblocks in the sales process.
    * Regularly review and refine the sales process to identify and eliminate bottlenecks.
    """,
    "visualization_suggestions": """
    * Line charts showing the average time to close over different time periods (e.g., monthly or quarterly).
    * Funnel charts to visualize the drop-off at each stage of the sales process.
    """,
    "risk_warnings": """
    * Extended time to close may result in lost opportunities and revenue.
    * Rapidly decreasing time to close may indicate a focus on quantity over quality, leading to potential customer dissatisfaction.
    """,
    "tracking_tools": """
    * Customer Relationship Management (CRM) software to track and manage lead interactions and progress.
    * Sales acceleration platforms to automate and streamline repetitive tasks in the sales process.
    """,
    "integration_points": """
    * Integrate time to close data with marketing analytics to understand the quality of leads generated by different campaigns.
    * Link with customer feedback systems to identify potential areas for improvement in the sales process.
    """,
    "change_impact_analysis": """
    * Shortening time to close may increase sales efficiency but could also impact the thoroughness of lead qualification.
    * Significantly lengthening time to close may indicate a need for reevaluation of sales strategies and resource allocation.
    """,
    "metadata_": {"modules": ["OUTSIDE_SALES"], "source": "kpidepot.com", "import_date": "2025-11-07", "required_objects": ["Customer", "Customer Advocacy Program", "Customer Cohort", "Customer Community", "Customer Education", "Customer Feedback", "Customer Goal", "Customer Health Record", "Customer Journey", "Customer Onboarding", "Customer Segment", "Customer Success Manager", "Deal", "Lead", "Lead Qualification", "Lost Sale", "Opportunity", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"]},
    "modules": ["OUTSIDE_SALES"],
    "module_code": "OUTSIDE_SALES",
}
