"""
Number of Leads Generated

The total count of potential customers or leads generated by the sales development team in a given period.
"""

NUMBER_OF_LEADS_GENERATED = {
    "code": "NUMBER_OF_LEADS_GENERATED",
    "name": "Number of Leads Generated",
    "description": "The total count of potential customers or leads generated by the sales development team in a given period.",
    "formula": "Count of New Leads Acquired",
    "calculation_formula": "Count of New Leads Acquired",
    "category": "Sales Development",
    "is_active": True,
    "full_kpi_definition": "Complete definition for Number of Leads Generated to be added.",
    "trend_analysis": """


    * An increasing number of leads generated may indicate improved marketing efforts or a growing market demand.
    * A decreasing count of leads could signal a need for sales development process optimization or a decline in market interest.
    
    
    """,
    "diagnostic_questions": """


    * What channels or strategies are most effective in generating leads for the sales development team?
    * Are there specific industries or segments where lead generation is particularly strong or weak?
    
    
    """,
    "actionable_tips": """


    * Implement lead scoring to prioritize high-quality leads for the sales team.
    * Regularly review and update lead generation strategies based on performance data and market trends.
    * Provide ongoing training and support for the sales development team to enhance lead generation skills.
    
    
    """,
    "visualization_suggestions": """


    * Line charts showing the trend of leads generated over time.
    * Pie charts to visualize the distribution of leads by source or industry.
    
    
    """,
    "risk_warnings": """


    * A low number of leads may lead to missed sales opportunities and revenue growth.
    * Over-reliance on a single lead generation channel or strategy can create vulnerability to market changes or disruptions.
    
    
    """,
    "tracking_tools": """


    * Customer Relationship Management (CRM) software to track and manage leads effectively.
    * Marketing automation platforms to streamline lead generation and nurturing processes.
    
    
    """,
    "integration_points": """


    * Integrate lead generation data with sales performance metrics to measure the effectiveness of lead conversion.
    * Link lead generation efforts with customer relationship management systems for seamless lead-to-customer transition.
    
    
    """,
    "change_impact_analysis": """


    * Improving lead generation can positively impact sales conversion rates and overall revenue.
    * However, a decrease in leads may require adjustments in sales strategies and resource allocation.
    
    
    """,
    "metadata_": {"modules": ["SALES_DEVELOPMENT"], "source": "kpidepot.com", "import_date": "2025-11-07", "required_objects": ["Customer", "Lead", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"], "last_validated": "2025-11-10T13:49:33.091228"},
    "required_objects": [],
    "modules": ["SALES_DEVELOPMENT"],
    "module_code": "SALES_DEVELOPMENT",
    "sample_data": {
        "time_series": {
                "dates": [
                        "2024-12-15",
                        "2025-01-14",
                        "2025-02-13",
                        "2025-03-15",
                        "2025-04-14",
                        "2025-05-14",
                        "2025-06-13",
                        "2025-07-13",
                        "2025-08-12",
                        "2025-09-11",
                        "2025-10-11",
                        "2025-11-10"
                ],
                "values": [
                        48.03,
                        50.81,
                        55.16,
                        44.65,
                        51.59,
                        52.62,
                        52.09,
                        49.38,
                        40.23,
                        59.14,
                        54.69,
                        45.54
                ],
                "unit": "%"
        },
        "current": {
                "value": 45.54,
                "unit": "%",
                "change": -9.15,
                "change_percent": -16.7,
                "trend": "stable"
        },
        "statistics": {
                "average": 50.33,
                "min": 40.23,
                "max": 59.14,
                "unit": "%"
        },
        "breakdown": [
                {
                        "category": "Category A",
                        "value": 12.81,
                        "percentage": 28.1
                },
                {
                        "category": "Category B",
                        "value": 5.41,
                        "percentage": 11.9
                },
                {
                        "category": "Category C",
                        "value": 7.9,
                        "percentage": 17.3
                },
                {
                        "category": "Category D",
                        "value": 5.68,
                        "percentage": 12.5
                },
                {
                        "category": "Other",
                        "value": 13.74,
                        "percentage": 30.2
                }
        ],
        "metadata": {
                "generated_date": "2025-11-10T13:43:23.708673",
                "data_points": 12,
                "kpi_type": "percentage",
                "kpi_name": "Number of Leads Generated"
        }
    },
}
