"""
Partner Lifecycle Value

The total value a partner contributes to the company throughout the duration of their relationship.
"""

PARTNER_LIFECYCLE_VALUE = {
    "code": "PARTNER_LIFECYCLE_VALUE",
    "name": "Partner Lifecycle Value",
    "description": "The total value a partner contributes to the company throughout the duration of their relationship.",
    "formula": "Total Revenue from Partner Over Lifetime of Relationship",
    "calculation_formula": "Total Revenue from Partner Over Lifetime of Relationship",
    "category": "Channel Sales",
    "is_active": True,
    "full_kpi_definition": "Complete definition for Partner Lifecycle Value to be added.",
    "trend_analysis": """


    * Increasing partner lifecycle value may indicate successful long-term partnerships and effective account management.
    * Decreasing value could signal dissatisfaction among partners or a lack of ongoing support and engagement.
    
    
    """,
    "diagnostic_questions": """


    * What are the key factors that contribute to the overall value generated by our partners?
    * How do we measure and track the satisfaction and engagement levels of our partners throughout their lifecycle?
    
    
    """,
    "actionable_tips": """


    * Implement a comprehensive partner success program to continuously support and enable partners.
    * Regularly assess and adjust partner incentives and rewards to ensure ongoing motivation and satisfaction.
    * Invest in training and resources to help partners expand their capabilities and offerings.
    
    
    """,
    "visualization_suggestions": """


    * Line charts showing the trend of partner lifecycle value over time.
    * Pie charts to compare the contribution of different partners to the overall value.
    
    
    """,
    "risk_warnings": """


    * Low partner lifecycle value may lead to increased partner churn and loss of valuable relationships.
    * High partner lifecycle value from a small number of partners may pose a risk of over-reliance on a few key relationships.
    
    
    """,
    "tracking_tools": """


    * Customer Relationship Management (CRM) systems to track partner interactions and measure their impact on value.
    * Partner portal platforms to provide partners with resources and support, and track their engagement.
    
    
    """,
    "integration_points": """


    * Integrate partner lifecycle value with sales performance data to understand the correlation between partner value and sales outcomes.
    * Link partner lifecycle value with marketing analytics to assess the effectiveness of partner-focused marketing efforts.
    
    
    """,
    "change_impact_analysis": """


    * Increasing partner lifecycle value can lead to higher overall sales and revenue, but may also require additional resources and support.
    * Decreasing partner lifecycle value can impact overall market share and competitive positioning.
    
    
    """,
    "metadata_": {"modules": ["CHANNEL_SALES"], "source": "kpidepot.com", "import_date": "2025-11-07", "required_objects": ["Channel Conflict", "Channel Deal", "Channel Market", "Channel Partner", "Customer", "Deal", "Lead", "Opportunity", "Partner Agreement", "Partner Incentive", "Partner Performance Scorecard", "Partner Portal", "Partner Training", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"], "last_validated": "2025-11-10T13:49:33.203756"},
    "required_objects": [],
    "modules": ["CHANNEL_SALES"],
    "module_code": "CHANNEL_SALES",
    "sample_data": {
        "time_series": {
                "dates": [
                        "2024-12-15",
                        "2025-01-14",
                        "2025-02-13",
                        "2025-03-15",
                        "2025-04-14",
                        "2025-05-14",
                        "2025-06-13",
                        "2025-07-13",
                        "2025-08-12",
                        "2025-09-11",
                        "2025-10-11",
                        "2025-11-10"
                ],
                "values": [
                        95224.18,
                        94059.5,
                        87243.03,
                        90521.63,
                        88195.07,
                        86104.0,
                        89922.01,
                        98754.49,
                        84590.03,
                        94449.41,
                        88700.78,
                        84634.72
                ],
                "unit": "$"
        },
        "current": {
                "value": 84634.72,
                "unit": "$",
                "change": -4066.06,
                "change_percent": -4.6,
                "trend": "stable"
        },
        "statistics": {
                "average": 90199.9,
                "min": 84590.03,
                "max": 98754.49,
                "unit": "$"
        },
        "breakdown": [
                {
                        "category": "Category A",
                        "value": 20705.97,
                        "percentage": 24.5
                },
                {
                        "category": "Category B",
                        "value": 20606.91,
                        "percentage": 24.3
                },
                {
                        "category": "Category C",
                        "value": 6509.86,
                        "percentage": 7.7
                },
                {
                        "category": "Category D",
                        "value": 10344.27,
                        "percentage": 12.2
                },
                {
                        "category": "Other",
                        "value": 26467.71,
                        "percentage": 31.3
                }
        ],
        "metadata": {
                "generated_date": "2025-11-10T13:43:23.878189",
                "data_points": 12,
                "kpi_type": "currency",
                "kpi_name": "Partner Lifecycle Value"
        }
    },
}
