"""
Partner Annual Revenue Growth

The year-over-year revenue growth generated by each channel partner, indicating their sales performance.
"""

PARTNER_ANNUAL_REVENUE_GROWTH = {
    "code": "PARTNER_ANNUAL_REVENUE_GROWTH",
    "name": "Partner Annual Revenue Growth",
    "description": "The year-over-year revenue growth generated by each channel partner, indicating their sales performance.",
    "formula": "((Current Year Revenue from Partner - Previous Year Revenue from Partner) / Previous Year Revenue from Partner) * 100",
    "calculation_formula": "((Current Year Revenue from Partner - Previous Year Revenue from Partner) / Previous Year Revenue from Partner) * 100",
    "category": "Channel Sales",
    "is_active": True,
    "full_kpi_definition": "Complete definition for Partner Annual Revenue Growth to be added.",
    "trend_analysis": """


    * Increasing partner annual revenue growth may indicate successful sales strategies or expanding market opportunities.
    * Decreasing growth could signal market saturation, increased competition, or ineffective partner management.
    
    
    """,
    "diagnostic_questions": """


    * Are there specific products or services that are driving the revenue growth for each partner?
    * How does the revenue growth of each partner compare to industry benchmarks or market trends?
    
    
    """,
    "actionable_tips": """


    * Provide targeted sales training and support to help partners capitalize on new market opportunities.
    * Regularly review and adjust partner incentive programs to align with changing market dynamics.
    * Encourage partners to diversify their product or service offerings to stimulate revenue growth.
    
    
    """,
    "visualization_suggestions": """


    * Line charts showing year-over-year revenue growth for each partner.
    * Pie charts comparing the contribution of different products or services to overall revenue growth for each partner.
    
    
    """,
    "risk_warnings": """


    * Over-reliance on a small number of partners for revenue growth can create vulnerability to market shifts or partner performance issues.
    * Stagnant or declining revenue growth may lead to partner dissatisfaction and disengagement.
    
    
    """,
    "tracking_tools": """


    * Customer Relationship Management (CRM) systems to track partner performance and identify growth opportunities.
    * Business Intelligence (BI) tools to analyze market trends and identify potential areas for revenue growth.
    
    
    """,
    "integration_points": """


    * Integrate partner revenue growth data with sales and marketing systems to align strategies and resources with partner performance.
    * Link revenue growth metrics with financial systems to assess the impact on overall company performance.
    
    
    """,
    "change_impact_analysis": """


    * Improving partner annual revenue growth can lead to increased market share and profitability for the organization.
    * Conversely, declining growth may require strategic shifts in partner management and market approach to maintain competitiveness.
    
    
    """,
    "metadata_": {"modules": ["CHANNEL_SALES"], "source": "kpidepot.com", "import_date": "2025-11-07", "required_objects": ["Channel Conflict", "Channel Deal", "Channel Market", "Channel Partner", "Customer", "Partner Agreement", "Partner Incentive", "Partner Performance Scorecard", "Partner Portal", "Partner Training", "Performance Benchmark", "Performance Scorecard", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"], "last_validated": "2025-11-10T13:49:33.177708"},
    "required_objects": [],
    "modules": ["CHANNEL_SALES"],
    "module_code": "CHANNEL_SALES",
    "sample_data": {
        "time_series": {
                "dates": [
                        "2024-12-15",
                        "2025-01-14",
                        "2025-02-13",
                        "2025-03-15",
                        "2025-04-14",
                        "2025-05-14",
                        "2025-06-13",
                        "2025-07-13",
                        "2025-08-12",
                        "2025-09-11",
                        "2025-10-11",
                        "2025-11-10"
                ],
                "values": [
                        61492.08,
                        61994.62,
                        61561.77,
                        66570.35,
                        64306.9,
                        60276.9,
                        55887.84,
                        65778.18,
                        57411.7,
                        68331.06,
                        54770.18,
                        68467.83
                ],
                "unit": "$"
        },
        "current": {
                "value": 68467.83,
                "unit": "$",
                "change": 13697.65,
                "change_percent": 25.0,
                "trend": "stable"
        },
        "statistics": {
                "average": 62237.45,
                "min": 54770.18,
                "max": 68467.83,
                "unit": "$"
        },
        "breakdown": [
                {
                        "category": "Category A",
                        "value": 16308.6,
                        "percentage": 23.8
                },
                {
                        "category": "Category B",
                        "value": 12221.83,
                        "percentage": 17.9
                },
                {
                        "category": "Category C",
                        "value": 9279.32,
                        "percentage": 13.6
                },
                {
                        "category": "Category D",
                        "value": 6838.91,
                        "percentage": 10.0
                },
                {
                        "category": "Other",
                        "value": 23819.17,
                        "percentage": 34.8
                }
        ],
        "metadata": {
                "generated_date": "2025-11-10T13:43:23.844766",
                "data_points": 12,
                "kpi_type": "currency",
                "kpi_name": "Partner Annual Revenue Growth"
        }
    },
}
