"""
Analytics Models Package

This package contains the hierarchical analytics model structure:
- Industry: Top-level container for value chains
- ValueChain: Container for modules
- Module: Contains object models
- ObjectModel: Unified model definition and instance (includes schema and data values)
- ObjectAttribute: Defines attributes for object models
- KPI: Comprehensive Key Performance Indicators with detailed definitions,
  insights, measurement approaches, formulas, trend analysis, diagnostic
  questions, actionable steps, visualization suggestions, risk warnings,
  tracking tools, integration points, and change impact analysis.
  
KPIs support derivation from parent KPIs for creating custom, business-specific
metrics while maintaining traceability to source definitions.
"""

from .db_models import (
    Industry,
    ValueChain,
    Module,
    ObjectModel,
    ObjectAttribute,
    KPI,
    Benchmark,
    Country,
    Region,
    MetropolitanStatisticalArea,
    Client,
    ClientRole,
    ClientModulePermission,
    RoleObjectModelPermission,
    RoleObjectPermission,
    RoleKPIPermission,
    RoleAttributePermission,
)

from .schemas import (
    IndustryCreate,
    IndustryUpdate,
    IndustryRead,
    ValueChainCreate,
    ValueChainUpdate,
    ValueChainRead,
    ModuleCreate,
    ModuleUpdate,
    ModuleRead,
    ObjectModelCreate,
    ObjectModelUpdate,
    ObjectModelRead,
    ObjectAttributeCreate,
    ObjectAttributeUpdate,
    ObjectAttributeRead,
    KPICreate,
    KPIUpdate,
    KPIRead,
    BenchmarkCreate,
    BenchmarkUpdate,
    BenchmarkRead,
    CountryCreate,
    CountryUpdate,
    CountryRead,
    RegionCreate,
    RegionUpdate,
    RegionRead,
    MetropolitanStatisticalAreaCreate,
    MetropolitanStatisticalAreaUpdate,
    MetropolitanStatisticalAreaRead,
    ClientCreate,
    ClientUpdate,
    ClientRead,
    ClientRoleCreate,
    ClientRoleUpdate,
    ClientRoleRead,
    ClientModulePermissionCreate,
    ClientModulePermissionUpdate,
    ClientModulePermissionRead,
    RoleObjectModelPermissionCreate,
    RoleObjectModelPermissionUpdate,
    RoleObjectModelPermissionRead,
    RoleObjectPermissionCreate,
    RoleObjectPermissionUpdate,
    RoleObjectPermissionRead,
    RoleKPIPermissionCreate,
    RoleKPIPermissionUpdate,
    RoleKPIPermissionRead,
    RoleAttributePermissionCreate,
    RoleAttributePermissionUpdate,
    RoleAttributePermissionRead,
)

__all__ = [
    # Database Models
    "Industry",
    "ValueChain",
    "Module",
    "ObjectModel",
    "ObjectAttribute",
    "KPI",
    "Benchmark",
    "Country",
    "Region",
    "MetropolitanStatisticalArea",
    "Client",
    "ClientRole",
    "ClientModulePermission",
    "RoleObjectModelPermission",
    "RoleObjectPermission",
    "RoleKPIPermission",
    "RoleAttributePermission",
    # Schemas
    "IndustryCreate",
    "IndustryUpdate",
    "IndustryRead",
    "ValueChainCreate",
    "ValueChainUpdate",
    "ValueChainRead",
    "ModuleCreate",
    "ModuleUpdate",
    "ModuleRead",
    "ObjectModelCreate",
    "ObjectModelUpdate",
    "ObjectModelRead",
    "ObjectAttributeCreate",
    "ObjectAttributeUpdate",
    "ObjectAttributeRead",
    "KPICreate",
    "KPIUpdate",
    "KPIRead",
    "BenchmarkCreate",
    "BenchmarkUpdate",
    "BenchmarkRead",
    "CountryCreate",
    "CountryUpdate",
    "CountryRead",
    "RegionCreate",
    "RegionUpdate",
    "RegionRead",
    "MetropolitanStatisticalAreaCreate",
    "MetropolitanStatisticalAreaUpdate",
    "MetropolitanStatisticalAreaRead",
    "ClientCreate",
    "ClientUpdate",
    "ClientRead",
    "ClientRoleCreate",
    "ClientRoleUpdate",
    "ClientRoleRead",
    "ClientModulePermissionCreate",
    "ClientModulePermissionUpdate",
    "ClientModulePermissionRead",
    "RoleObjectModelPermissionCreate",
    "RoleObjectModelPermissionUpdate",
    "RoleObjectModelPermissionRead",
    "RoleObjectPermissionCreate",
    "RoleObjectPermissionUpdate",
    "RoleObjectPermissionRead",
    "RoleKPIPermissionCreate",
    "RoleKPIPermissionUpdate",
    "RoleKPIPermissionRead",
    "RoleAttributePermissionCreate",
    "RoleAttributePermissionUpdate",
    "RoleAttributePermissionRead",
]
