"""
Logistics Module

Auto-generated by KPI Excel Processor
"""

from analytics_models import Module

LOGISTICS = Module(
    name="Logistics",
    code="LOGISTICS",
    description="Logistics analytics and performance tracking",
    display_order=1,
    is_active=True,
    metadata_={
        "value_chains": ["SUPPLY_CHAIN"],
        "industries": ["RETAIL", "MANUFACTURING"],
        "associated_object_models": ["CUSTOMER", "DELIVERY", "INVENTORY", "LEAD", "ORDER"],
        "associated_kpis": [
            "back_order_rate",
            "carrier_compliance_rate",
            "claims_percentage",
            "co2_emissions_per_ton_mile",
            "cost_per_delivery_point",
            "cost_per_shipment",
            "cost_per_ton_mile",
            "cross_docking_efficiency",
            "customer_claim_rate",
            "customer_satisfaction_with_delivery",
            "damage_free_delivery_rate",
            "delivery_distance",
            "delivery_in_full_on_time_difot_rate",
            "delivery_route_optimization_rate",
            "delivery_trip_standard_deviation",
            "detention_time",
            "dock_to_stock_cycle_time",
            "driver_retention_rate",
            "empty_miles",
            "fleet_utilization_rate",
            "freight_cost_as_a_percentage_of_sales",
            "inventory_carrying_cost",
            "inventory_turnover_ratio",
            "linehaul_efficiency",
            "load_factor",
            "lost_sales_due_to_stockouts",
            "miles_per_gallon_mpg_of_fleet",
            "on_time_delivery_rate",
            "on_time_pickup_rate",
            "order_to_delivery_lead_time",
            "order_tracking_efficiency",
            "picking_accuracy",
            "pickup_and_delivery_productivity",
            "return_order_rate",
            "shipment_lead_time",
            "transportation_cost_per_unit",
            "transportation_order_lead_time",
            "truck_turnaround_time",
            "vehicle_fill_rate",
            "vehicle_maintenance_costs_per_mile",
            "warehouse_efficiency",
            "warehouse_safety_incidents_rate",
            "yield_per_mile"
        ]
    }
)
