"""
Packing Module

Auto-generated by KPI Excel Processor
"""

from analytics_models import Module

PACKING = Module(
    name="Packing",
    code="PACKING",
    description="Packing analytics and performance tracking",
    display_order=1,
    is_active=True,
    metadata_={
        "value_chains": ["SUPPLY_CHAIN"],
        "industries": ["RETAIL", "MANUFACTURING"],
        "associated_object_models": ["CUSTOMER", "DELIVERY", "INVENTORY", "LEAD", "ORDER"],
        "associated_kpis": [
            "customer_satisfaction_with_packaging",
            "environmental_impact_of_packaging",
            "material_utilization_rate",
            "order_fulfillment_lead_time",
            "order_packing_accuracy",
            "order_packing_capacity",
            "packaging_compliance_rate",
            "packaging_damage_rate",
            "packaging_efficiency_rate",
            "packaging_innovation_index",
            "packaging_return_on_investment_roi",
            "packaging_sustainability_score",
            "packaging_waste_volume",
            "packing_cost_per_unit",
            "packing_cost_variance",
            "packing_equipment_utilization_rate",
            "packing_error_rate",
            "packing_error_resolution_time",
            "packing_flexibility",
            "packing_inventory_turnover_rate",
            "packing_labor_productivity",
            "packing_lead_time",
            "packing_material_cost_variability",
            "packing_process_cycle_efficiency",
            "packing_process_downtime",
            "packing_quality_control_rate",
            "packing_safety_incident_rate",
            "packing_space_utilization",
            "packing_station_utilization",
            "packing_throughput_rate",
            "return_rate_due_to_packing_errors",
            "supply_chain_packing_cycle_time",
            "sustainable_packaging_index",
            "time_to_pack_per_order"
        ]
    }
)
