"""
Logistics Module

Auto-generated by KPI Excel Processor
"""

from analytics_models import Module

LOGISTICS = Module(
    name="Logistics",
    code="LOGISTICS",
    description="Logistics analytics and performance tracking",
    display_order=1,
    is_active=True,
    metadata_={
        "value_chains": ["SUPPLY_CHAIN"],
        "industries": ["RETAIL", "MANUFACTURING"],
        "associated_object_models": ["CUSTOMER", "DELIVERY", "INVENTORY", "LEAD", "ORDER"],
        "associated_kpis": [
            "delivery_distance",
            "miles_per_gallon_mpg_of_fleet",
            "warehouse_efficiency",
            "back_order_rate",
            "carrier_compliance_rate",
            "claims_percentage"
            # ... and 37 more
        ]
    }
)
