"""
Sales Mgmt Value Chain

Auto-generated by KPI Excel Processor
"""

SALES_MGMT = {
    "code": "SALES_MGMT",
    "name": "Sales Mgmt",
    "display_name": "Sales Mgmt",
    "description": "Sales Mgmt operations and optimization",
    "associated_modules": [],  # Will be populated by governance suite
    "metadata_": {
        "category": "cross_industry",
        "industries": ["RETAIL", "MANUFACTURING"],
        "display_order": 1,
        "is_active": True
    }
}
