"""
Annual Recurring Revenue (ARR) KPI

The amount of revenue that the outside sales team generates annually through renewals, upgrades, and new sales.
"""

from analytics_models import KPI

ANNUAL_RECURRING_REVENUE_ARR = KPI(
    name="Annual Recurring Revenue (ARR)",
    code="ANNUAL_RECURRING_REVENUE_ARR",
    category="Outside Sales",
    
    # Core Definition
    description="The amount of revenue that the outside sales team generates annually through renewals, upgrades, and new sales.",
    kpi_definition="The amount of revenue that the outside sales team generates annually through renewals, upgrades, and new sales.",
    expected_business_insights="Provides insight into the stable and predictable portion of revenue, essential for long-term business planning.",
    measurement_approach="Tracks the total predictable and recurring revenue generated by customers over a one-year period.",
    
    # Formula
    formula="Sum of all recurring revenue from customers in one year",
    calculation_formula="Sum of all recurring revenue from customers in one year",
    
    # Analysis
    trend_analysis="""
    * Increasing ARR may indicate successful customer retention and upselling efforts.
    * Decreasing ARR could signal customer churn or a decline in the value of sales.
    """,
    diagnostic_questions="""
    * What percentage of the ARR comes from renewals versus new sales?
    * Are there specific customer segments or products that contribute significantly to the ARR?
    """,
    
    # Action & Visualization
    actionable_tips="""
    * Implement customer success programs to improve retention and upsell opportunities.
    * Focus on identifying and targeting high-value customer segments for new sales.
    """,
    visualization_suggestions="""
    * Line charts showing the trend of ARR over time.
    * Pie charts to illustrate the contribution of renewals, upgrades, and new sales to the overall ARR.
    """,
    
    # Risk & Integration
    risk_warnings="""
    * Dependence on a few key accounts for a large portion of the ARR can pose a risk if those accounts are lost.
    * Failure to adapt to changing customer needs and market trends may lead to declining ARR.
    """,
    tracking_tools="""
    * Customer relationship management (CRM) software to track customer interactions and identify upsell opportunities.
    * Business intelligence tools for analyzing customer behavior and identifying opportunities for increasing ARR.
    """,
    integration_points="""
    * Integrate ARR tracking with sales and marketing systems to align efforts towards increasing recurring revenue.
    * Link ARR data with customer support systems to identify opportunities for upselling or cross-selling.
    """,
    change_impact_analysis="""
    * Increasing ARR can lead to higher customer lifetime value and overall revenue growth.
    * However, focusing solely on ARR may neglect the importance of new customer acquisition and market expansion.
    """,
    
    is_active=True,
    metadata_={
        "modules": ["OUTSIDE_SALES", "SALES_OPERATIONS"],
        "source": "kpidepot.com",
        "import_date": "2025-11-07",
        "required_objects": ["Contract", "Customer", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"]
    }
)
