"""
Marketing Qualified Leads (MQL) KPI

Module: Business Development
"""

from analytics_models import KPI

MARKETING_QUALIFIED_LEADS_MQL = KPI(
    name="Marketing Qualified Leads (MQL)",
    code="MARKETING_QUALIFIED_LEADS_MQL",
    description="The number of leads that have shown interest in a company's offerings and are considered more likely to become customers than other leads.",
    
    # Definition & Context
    kpi_definition="The number of leads that have shown interest in a company's offerings and are considered more likely to become customers than other leads.",
    expected_business_insights="Assesses the quality of leads generated by marketing efforts and assists in marketing performance evaluation.",
    measurement_approach="Measures the number of leads deemed more likely to become customers based on predefined criteria.",
    
    # Calculation
    formula="Number of Leads Meeting MQL Criteria",
    
    # Analysis
    trend_analysis="Increasing MQLs over time may indicate successful marketing campaigns or improved lead generation strategies. A decreasing trend could signal a decline in market interest or a need for adjustments in the marketing approach.",
    diagnostic_questions=['What specific marketing channels or campaigns are generating the most MQLs?', 'Are there any common characteristics or behaviors among MQLs that can be leveraged for more targeted marketing?'],
    actionable_steps={
        "operational": ['Refine lead scoring criteria to better qualify MQLs and prioritize follow-up efforts.'],
        "strategic": ['Implement personalized nurturing campaigns to further engage and convert MQLs into customers.', 'Regularly review and update marketing strategies to align with changing market dynamics and customer preferences.']
    },
    
    # Visualization
    visualization_suggestions=[
        {"type": "chart", "description": viz} for viz in ['Line charts showing MQL trends over time and by different marketing channels.', 'Funnel charts to visualize the conversion rates from MQLs to customers at various stages of the sales process.']
    ],
    risk_warnings=['A high volume of MQLs without corresponding conversions may indicate a disconnect between marketing and sales efforts.', 'Low MQL numbers could lead to reduced sales pipeline and revenue opportunities.'],
    
    # Tools & Integration
    suggested_tracking_tools=['Marketing automation platforms like HubSpot or Marketo to track and manage MQLs throughout the sales funnel.', 'Data analytics tools to gain insights into MQL behavior and preferences for more targeted marketing.'],
    integration_points=['Integrate MQL tracking with CRM systems to ensure seamless handoff of qualified leads to the sales team.', 'Connect MQL data with customer support systems to provide a more personalized experience for potential customers.'],
    
    # Impact
    change_impact="Increasing MQLs can lead to higher sales revenue and customer acquisition, but may also require additional resources for effective lead management. On the other hand, a decrease in MQLs could impact the overall sales pipeline and revenue projections.",
    
    # Metadata
    category="Business Development",
    is_active=True,
    metadata_={
        "modules": ["BUS_DEV"],
        "value_chains": ["SALES_MGMT"],
        "source": "kpidepot.com",
        "required_objects": ["Customer", "Lead", "Meeting", "Quarterly Business Review"]
    }
)
