"""
Number of Leads Generated KPI

The total count of potential customers or leads generated by the sales development team in a given period.
"""

from analytics_models import KPI

NUMBER_OF_LEADS_GENERATED = KPI(
    name="Number of Leads Generated",
    code="NUMBER_OF_LEADS_GENERATED",
    category="Sales Development",
    
    # Core Definition
    description="The total count of potential customers or leads generated by the sales development team in a given period.",
    kpi_definition="The total count of potential customers or leads generated by the sales development team in a given period.",
    expected_business_insights="Evaluates the effectiveness of marketing campaigns and lead generation strategies.",
    measurement_approach="Measures the total amount of new leads produced by marketing efforts.",
    
    # Formula
    formula="Count of New Leads Acquired",
    calculation_formula="Count of New Leads Acquired",
    
    # Analysis
    trend_analysis="""
    * An increasing number of leads generated may indicate improved marketing efforts or a growing market demand.
    * A decreasing count of leads could signal a need for sales development process optimization or a decline in market interest.
    """,
    diagnostic_questions="""
    * What channels or strategies are most effective in generating leads for the sales development team?
    * Are there specific industries or segments where lead generation is particularly strong or weak?
    """,
    
    # Action & Visualization
    actionable_tips="""
    * Implement lead scoring to prioritize high-quality leads for the sales team.
    * Regularly review and update lead generation strategies based on performance data and market trends.
    * Provide ongoing training and support for the sales development team to enhance lead generation skills.
    """,
    visualization_suggestions="""
    * Line charts showing the trend of leads generated over time.
    * Pie charts to visualize the distribution of leads by source or industry.
    """,
    
    # Risk & Integration
    risk_warnings="""
    * A low number of leads may lead to missed sales opportunities and revenue growth.
    * Over-reliance on a single lead generation channel or strategy can create vulnerability to market changes or disruptions.
    """,
    tracking_tools="""
    * Customer Relationship Management (CRM) software to track and manage leads effectively.
    * Marketing automation platforms to streamline lead generation and nurturing processes.
    """,
    integration_points="""
    * Integrate lead generation data with sales performance metrics to measure the effectiveness of lead conversion.
    * Link lead generation efforts with customer relationship management systems for seamless lead-to-customer transition.
    """,
    change_impact_analysis="""
    * Improving lead generation can positively impact sales conversion rates and overall revenue.
    * However, a decrease in leads may require adjustments in sales strategies and resource allocation.
    """,
    
    is_active=True,
    metadata_={
        "modules": ["SALES_DEVELOPMENT"],
        "source": "kpidepot.com",
        "import_date": "2025-11-07",
        "required_objects": ["Customer", "Lead", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"]
    }
)
