"""
Meeting Booking Rate

The rate at which initial sales calls or meetings are booked with potential clients.
"""

MEETING_BOOKING_RATE = {
    "code": "MEETING_BOOKING_RATE",
    "name": "Meeting Booking Rate",
    "description": "The rate at which initial sales calls or meetings are booked with potential clients.",
    "formula": "(Total Meetings Booked / Total Outreach Attempts) * 100",
    "calculation_formula": "(Total Meetings Booked / Total Outreach Attempts) * 100",
    "category": "Sales Development",
    "is_active": True,
    "full_kpi_definition": "Complete definition for Meeting Booking Rate to be added.",
    "trend_analysis": """

    * An increasing meeting booking rate may indicate improved lead generation or a more effective sales outreach strategy.
    * A decreasing rate could signal a decline in the quality of leads or a need for sales process optimization.
    
    """,
    "diagnostic_questions": """

    * Are there specific sales channels or sources that consistently yield higher meeting booking rates?
    * How does our meeting booking rate compare with industry benchmarks or historical performance?
    
    """,
    "actionable_tips": """

    * Refine targeting and qualification criteria to focus on higher-potential leads.
    * Provide additional sales training and resources to improve the effectiveness of sales outreach efforts.
    * Implement a lead scoring system to prioritize leads with higher potential for meeting bookings.
    
    """,
    "visualization_suggestions": """

    * Line charts showing the trend of meeting booking rates over time.
    * Pie charts to visualize the distribution of meeting bookings by sales channel or lead source.
    
    """,
    "risk_warnings": """

    * A consistently low meeting booking rate can lead to missed sales opportunities and revenue loss.
    * A high meeting booking rate with low conversion rates may indicate a need for better lead qualification processes.
    
    """,
    "tracking_tools": """

    * Customer Relationship Management (CRM) software to track and analyze lead interactions and meeting bookings.
    * Sales engagement platforms to streamline and optimize sales outreach activities.
    
    """,
    "integration_points": """

    * Integrate meeting booking rate data with sales performance metrics to assess the impact on overall sales effectiveness.
    * Link meeting booking rate tracking with marketing analytics to understand the quality of leads generated by different marketing campaigns.
    
    """,
    "change_impact_analysis": """

    * Improving the meeting booking rate can lead to increased sales opportunities and revenue growth.
    * However, a significant increase in meeting bookings without a corresponding increase in conversion rates may strain sales resources and affect overall sales productivity.
    
    """,
    "metadata_": {"modules": ["SALES_DEVELOPMENT"], "source": "kpidepot.com", "import_date": "2025-11-07", "required_objects": ["Call", "Customer", "Customer Success Manager", "Lead", "Meeting", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"], "last_validated": "2025-11-10T13:43:23.654355"},
    "required_objects": [],
    "modules": ["SALES_DEVELOPMENT"],
    "module_code": "SALES_DEVELOPMENT",
    "sample_data": {
        "time_series": {
                "dates": [
                        "2024-12-15",
                        "2025-01-14",
                        "2025-02-13",
                        "2025-03-15",
                        "2025-04-14",
                        "2025-05-14",
                        "2025-06-13",
                        "2025-07-13",
                        "2025-08-12",
                        "2025-09-11",
                        "2025-10-11",
                        "2025-11-10"
                ],
                "values": [
                        70.72,
                        55.26,
                        66.01,
                        65.87,
                        63.92,
                        59.08,
                        55.24,
                        73.7,
                        70.2,
                        63.46,
                        72.31,
                        59.22
                ],
                "unit": "%"
        },
        "current": {
                "value": 59.22,
                "unit": "%",
                "change": -13.09,
                "change_percent": -18.1,
                "trend": "stable"
        },
        "statistics": {
                "average": 64.58,
                "min": 55.24,
                "max": 73.7,
                "unit": "%"
        },
        "breakdown": [
                {
                        "category": "Category A",
                        "value": 19.39,
                        "percentage": 32.7
                },
                {
                        "category": "Category B",
                        "value": 8.59,
                        "percentage": 14.5
                },
                {
                        "category": "Category C",
                        "value": 7.0,
                        "percentage": 11.8
                },
                {
                        "category": "Category D",
                        "value": 5.6,
                        "percentage": 9.5
                },
                {
                        "category": "Other",
                        "value": 18.64,
                        "percentage": 31.5
                }
        ],
        "metadata": {
                "generated_date": "2025-11-10T13:43:23.654355",
                "data_points": 12,
                "kpi_type": "percentage",
                "kpi_name": "Meeting Booking Rate"
        }
    },
}
