"""
Sales Growth

The percentage of revenue growth generated by the Business Development Team.
"""

SALES_GROWTH = {
    "code": "SALES_GROWTH",
    "name": "Sales Growth",
    "description": "The percentage of revenue growth generated by the Business Development Team.",
    "formula": "((Current Period Sales - Previous Period Sales) / Previous Period Sales) * 100",
    "calculation_formula": "((Current Period Sales - Previous Period Sales) / Previous Period Sales) * 100",
    "category": "Business Development",
    "is_active": True,
    "full_kpi_definition": "Complete definition for Sales Growth to be added.",
    "trend_analysis": "Trend analysis to be defined.",
    "diagnostic_questions": """

* What factors are influencing this metric?
* Are there any anomalies in the data?
    
    """,
    "actionable_tips": """

* Monitor this KPI regularly
* Set appropriate targets and thresholds
    
    """,
    "visualization_suggestions": """

* Line chart for time series analysis
* Bar chart for comparisons
    
    """,
    "risk_warnings": "* Monitor for significant deviations from expected values",
    "tracking_tools": "* CRM or analytics platform",
    "integration_points": "* Integrate with related business metrics",
    "change_impact_analysis": "Changes in this KPI may impact related business processes.",
    "metadata_": {"modules": ["BUSINESS_DEVELOPMENT"], "required_objects": [], "last_validated": "2025-11-10T13:43:24.404880"},
    "required_objects": [],
    "modules": ["BUSINESS_DEVELOPMENT"],
    "module_code": "BUSINESS_DEVELOPMENT",
    "sample_data": {
        "time_series": {
                "dates": [
                        "2024-12-15",
                        "2025-01-14",
                        "2025-02-13",
                        "2025-03-15",
                        "2025-04-14",
                        "2025-05-14",
                        "2025-06-13",
                        "2025-07-13",
                        "2025-08-12",
                        "2025-09-11",
                        "2025-10-11",
                        "2025-11-10"
                ],
                "values": [
                        445.43,
                        314.51,
                        326.95,
                        334.76,
                        330.94,
                        311.83,
                        332.2,
                        413.1,
                        425.25,
                        338.85,
                        423.47,
                        321.51
                ],
                "unit": "units"
        },
        "current": {
                "value": 321.51,
                "unit": "units",
                "change": -101.96,
                "change_percent": -24.1,
                "trend": "stable"
        },
        "statistics": {
                "average": 359.9,
                "min": 311.83,
                "max": 445.43,
                "unit": "units"
        },
        "breakdown": [
                {
                        "category": "Category A",
                        "value": 64.67,
                        "percentage": 20.1
                },
                {
                        "category": "Category B",
                        "value": 78.06,
                        "percentage": 24.3
                },
                {
                        "category": "Category C",
                        "value": 55.78,
                        "percentage": 17.3
                },
                {
                        "category": "Category D",
                        "value": 35.54,
                        "percentage": 11.1
                },
                {
                        "category": "Other",
                        "value": 87.46,
                        "percentage": 27.2
                }
        ],
        "metadata": {
                "generated_date": "2025-11-10T13:43:24.404880",
                "data_points": 12,
                "kpi_type": "metric",
                "kpi_name": "Sales Growth"
        }
    },
}
