"""
Partner Lifecycle Value KPI

The total value a partner contributes to the company throughout the duration of their relationship.
"""

from analytics_models import KPI

PARTNER_LIFECYCLE_VALUE = KPI(
    name="Partner Lifecycle Value",
    code="PARTNER_LIFECYCLE_VALUE",
    category="Channel Sales",
    
    # Core Definition
    description="The total value a partner contributes to the company throughout the duration of their relationship.",
    kpi_definition="The total value a partner contributes to the company throughout the duration of their relationship.",
    expected_business_insights="Helps evaluate the long-term value of partnerships and guides investment in partner development.",
    measurement_approach="Measures the total revenue a partner generates for the company over the duration of the relationship.",
    
    # Formula
    formula="Total Revenue from Partner Over Lifetime of Relationship",
    calculation_formula="Total Revenue from Partner Over Lifetime of Relationship",
    
    # Analysis
    trend_analysis="""
    * Increasing partner lifecycle value may indicate successful long-term partnerships and effective account management.
    * Decreasing value could signal dissatisfaction among partners or a lack of ongoing support and engagement.
    """,
    diagnostic_questions="""
    * What are the key factors that contribute to the overall value generated by our partners?
    * How do we measure and track the satisfaction and engagement levels of our partners throughout their lifecycle?
    """,
    
    # Action & Visualization
    actionable_tips="""
    * Implement a comprehensive partner success program to continuously support and enable partners.
    * Regularly assess and adjust partner incentives and rewards to ensure ongoing motivation and satisfaction.
    * Invest in training and resources to help partners expand their capabilities and offerings.
    """,
    visualization_suggestions="""
    * Line charts showing the trend of partner lifecycle value over time.
    * Pie charts to compare the contribution of different partners to the overall value.
    """,
    
    # Risk & Integration
    risk_warnings="""
    * Low partner lifecycle value may lead to increased partner churn and loss of valuable relationships.
    * High partner lifecycle value from a small number of partners may pose a risk of over-reliance on a few key relationships.
    """,
    tracking_tools="""
    * Customer Relationship Management (CRM) systems to track partner interactions and measure their impact on value.
    * Partner portal platforms to provide partners with resources and support, and track their engagement.
    """,
    integration_points="""
    * Integrate partner lifecycle value with sales performance data to understand the correlation between partner value and sales outcomes.
    * Link partner lifecycle value with marketing analytics to assess the effectiveness of partner-focused marketing efforts.
    """,
    change_impact_analysis="""
    * Increasing partner lifecycle value can lead to higher overall sales and revenue, but may also require additional resources and support.
    * Decreasing partner lifecycle value can impact overall market share and competitive positioning.
    """,
    
    is_active=True,
    metadata_={
        "modules": ["CHANNEL_SALES"],
        "source": "kpidepot.com",
        "import_date": "2025-11-07",
        "required_objects": ["Channel Conflict", "Channel Deal", "Channel Market", "Channel Partner", "Customer", "Deal", "Lead", "Opportunity", "Partner Agreement", "Partner Incentive", "Partner Performance Scorecard", "Partner Portal", "Partner Training", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"]
    }
)
