"""
Sales Growth KPI

Module: Business Development
"""

from analytics_models import KPI

SALES_GROWTH = KPI(
    name="Sales Growth",
    code="SALES_GROWTH",
    description="The percentage of revenue growth generated by the Business Development Team.",
    
    # Definition & Context
    kpi_definition="The percentage of revenue growth generated by the Business Development Team.",
    expected_business_insights="Indicates overall business performance and market share expansion.",
    measurement_approach="Calculates the increase in sales revenue over a specific period.",
    
    # Calculation
    formula="((Current Period Sales - Previous Period Sales) / Previous Period Sales) * 100",
    
    # Analysis
    trend_analysis="Consistent year-over-year sales growth may indicate effective business development strategies and market expansion. A sudden decline in sales growth could signal market saturation, increased competition, or ineffective sales tactics.",
    diagnostic_questions=['What specific products or services have contributed the most to our sales growth?', 'How does our sales growth compare to industry benchmarks or economic trends?'],
    actionable_steps={
        "operational": ['Invest in targeted marketing and sales campaigns to reach new customer segments or geographic areas.'],
        "strategic": ['Focus on upselling and cross-selling to existing customers to maximize revenue potential.', 'Regularly review and adjust pricing strategies to optimize revenue generation.']
    },
    
    # Visualization
    visualization_suggestions=[
        {"type": "chart", "description": viz} for viz in ['Line charts showing sales growth over time, broken down by product or market segment.', 'Pie charts illustrating the contribution of different products or services to overall sales growth.']
    ],
    risk_warnings=['Rapid sales growth may strain operational resources and lead to fulfillment challenges.', 'Dependence on a small number of high-performing products for sales growth can create vulnerability to market shifts or product obsolescence.'],
    
    # Tools & Integration
    suggested_tracking_tools=['Customer Relationship Management (CRM) software to track and manage sales opportunities and customer interactions.', 'Business intelligence and analytics tools to identify trends and patterns in sales data.'],
    integration_points=['Integrate sales growth data with financial systems to understand the impact on revenue and profitability.', 'Link sales growth metrics with inventory and supply chain management systems to ensure adequate product availability.'],
    
    # Impact
    change_impact="Increasing sales growth may require additional investment in sales and marketing resources, impacting overall cost structure. Significant changes in sales growth can affect cash flow, inventory management, and production planning.",
    
    # Metadata
    category="Business Development",
    is_active=True,
    metadata_={
        "modules": ["BUS_DEV", "KEY_ACCOUNT_MANAGEMENT", "SALES_OPERATIONS", "SALES_STRATEGY"],
        "value_chains": ["SALES_MGMT"],
        "source": "kpidepot.com"
        "replaces": ["SALES_GROWTH_RATE"],
        "required_objects": ["Customer", "Quarterly Business Review", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"]
    }
)
