"""
Opportunity-to-Sale Ratio KPI

The ratio of sales opportunities that are converted into actual sales.
"""

from analytics_models import KPI

OPPORTUNITY_TO_SALE_RATIO = KPI(
    name="Opportunity-to-Sale Ratio",
    code="OPPORTUNITY_TO_SALE_RATIO",
    category="Outside Sales",
    
    # Core Definition
    description="The ratio of sales opportunities that are converted into actual sales.",
    kpi_definition="The ratio of sales opportunities that are converted into actual sales.",
    expected_business_insights="Highlights the effectiveness of the sales process in converting opportunities into revenue and can guide improvements in sales strategy.",
    measurement_approach="Compares the number of sales opportunities to the number of actual sales made.",
    
    # Formula
    formula="Number of Sales Made / Number of Opportunities * 100",
    calculation_formula="Number of Sales Made / Number of Opportunities * 100",
    
    # Analysis
    trend_analysis="""
    * An increasing opportunity-to-sale ratio may indicate improved lead quality or more effective sales strategies.
    * A decreasing ratio could signal issues in the sales process, such as ineffective follow-up or poor qualification of leads.
    """,
    diagnostic_questions="""
    * Are there specific stages in the sales funnel where opportunities are frequently lost?
    * What are the common reasons for opportunities not converting into sales, and how can those barriers be addressed?
    """,
    
    # Action & Visualization
    actionable_tips="""
    * Provide additional sales training and support to improve the conversion skills of the sales team.
    * Implement lead scoring to prioritize high-quality opportunities and focus efforts on those most likely to convert.
    * Regularly review and refine the sales process to identify and address any bottlenecks or inefficiencies.
    """,
    visualization_suggestions="""
    * Funnel charts to visualize the drop-off at each stage of the sales process.
    * Trend line graphs to track the ratio over time and identify any significant changes.
    """,
    
    # Risk & Integration
    risk_warnings="""
    * A consistently low opportunity-to-sale ratio may indicate fundamental issues in the sales approach or market fit.
    * High fluctuations in the ratio could lead to inconsistent revenue and forecasting challenges.
    """,
    tracking_tools="""
    * Customer Relationship Management (CRM) software to track and analyze the sales pipeline and opportunities.
    * Sales enablement tools to provide the sales team with the resources and support needed to effectively convert opportunities into sales.
    """,
    integration_points="""
    * Integrate the opportunity-to-sale ratio with marketing analytics to understand the quality of leads generated by different campaigns.
    * Link the ratio with customer feedback and satisfaction data to identify potential areas for improvement in the sales process.
    """,
    change_impact_analysis="""
    * Improving the opportunity-to-sale ratio can lead to increased revenue and better utilization of sales resources.
    * However, overly aggressive tactics to boost the ratio may result in a decline in customer satisfaction and long-term relationships.
    """,
    
    is_active=True,
    metadata_={
        "modules": ["OUTSIDE_SALES"],
        "source": "kpidepot.com",
        "import_date": "2025-11-07",
        "required_objects": ["Expansion Opportunity", "Lost Sale", "Opportunity", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"]
    }
)
