"""
Partner Pipeline Contribution KPI

The amount of potential sales revenue present in the sales pipeline due to channel partners, indicating their contribution to future sales.
"""

from analytics_models import KPI

PARTNER_PIPELINE_CONTRIBUTION = KPI(
    name="Partner Pipeline Contribution",
    code="PARTNER_PIPELINE_CONTRIBUTION",
    category="Channel Sales",
    
    # Core Definition
    description="The amount of potential sales revenue present in the sales pipeline due to channel partners, indicating their contribution to future sales.",
    kpi_definition="The amount of potential sales revenue present in the sales pipeline due to channel partners, indicating their contribution to future sales.",
    expected_business_insights="Provides visibility into future sales potential through the channel and informs sales forecasting.",
    measurement_approach="Evaluates the amount of revenue in the sales pipeline generated by channel partners.",
    
    # Formula
    formula="Total Value of Sales Pipeline Generated by Partners",
    calculation_formula="Total Value of Sales Pipeline Generated by Partners",
    
    # Analysis
    trend_analysis="""
    * Increasing partner pipeline contribution may indicate successful partner enablement and engagement.
    * Decreasing contribution could signal issues with partner relationships or lack of focus on channel sales.
    """,
    diagnostic_questions="""
    * Are there specific partners consistently contributing to the pipeline, and if not, why?
    * How does the partner pipeline contribution compare to direct sales pipeline contribution?
    """,
    
    # Action & Visualization
    actionable_tips="""
    * Invest in partner training and enablement to improve their ability to generate and manage pipeline opportunities.
    * Implement a lead distribution and tracking system to ensure partners are effectively managing their pipeline contributions.
    """,
    visualization_suggestions="""
    * Stacked bar charts comparing partner and direct sales pipeline contributions over time.
    * Line graphs showing the trend of partner pipeline contribution as a percentage of total sales pipeline.
    """,
    
    # Risk & Integration
    risk_warnings="""
    * Over-reliance on a few partners for pipeline contribution can create vulnerability if those relationships sour.
    * Low partner pipeline contribution may indicate a need for reevaluation of the partner program or strategy.
    """,
    tracking_tools="""
    * Customer Relationship Management (CRM) systems with partner management capabilities to track partner pipeline contributions.
    * Partner Relationship Management (PRM) platforms to provide partners with tools for managing their pipeline contributions.
    """,
    integration_points="""
    * Integrate partner pipeline contribution data with sales forecasting to better predict future revenue from channel sales.
    * Link partner pipeline contribution with incentive and commission systems to ensure partners are appropriately rewarded for their contributions.
    """,
    change_impact_analysis="""
    * Increasing partner pipeline contribution can lead to higher overall sales revenue and market reach.
    * However, a decrease in partner pipeline contribution may require a shift in resources towards direct sales efforts.
    """,
    
    is_active=True,
    metadata_={
        "modules": ["CHANNEL_SALES"],
        "source": "kpidepot.com",
        "import_date": "2025-11-07",
        "required_objects": ["Channel Conflict", "Channel Deal", "Channel Market", "Channel Partner", "Customer", "Partner Agreement", "Partner Incentive", "Partner Performance Scorecard", "Partner Portal", "Partner Training", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Pipeline", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"]
    }
)
