"""
Return on Sales Investment (ROSI) KPI

Module: Business Development
"""

from analytics_models import KPI

RETURN_ON_SALES_INVESTMENT_ROSI = KPI(
    name="Return on Sales Investment (ROSI)",
    code="RETURN_ON_SALES_INVESTMENT_ROSI",
    description="A metric that measures the profit generated by investments in the sales process, reflecting the efficiency and effectiveness of sales activities.",
    
    # Definition & Context
    kpi_definition="A metric that measures the profit generated by investments in the sales process, reflecting the efficiency and effectiveness of sales activities.",
    expected_business_insights="Assesses the efficiency of sales investments and guides budget allocation.",
    measurement_approach="Calculates the financial return on each dollar invested in sales activities.",
    
    # Calculation
    formula="(Gross Profit from Sales - Sales Investment) / Sales Investment",
    
    # Analysis
    trend_analysis="A rising ROSI may indicate increased effectiveness of sales activities or improved market conditions. A decreasing ROSI could signal inefficiencies in the sales process, increased competition, or changes in customer behavior.",
    diagnostic_questions=['What specific sales activities or strategies have contributed to the changes in ROSI?', 'How does our ROSI compare with industry benchmarks or with previous performance?'],
    actionable_steps={
        "operational": ['Invest in sales training and development to improve the effectiveness of sales teams.'],
        "strategic": ['Implement customer relationship management (CRM) systems to better track and manage sales activities.', 'Regularly review and adjust sales strategies based on market conditions and customer feedback.']
    },
    
    # Visualization
    visualization_suggestions=[
        {"type": "chart", "description": viz} for viz in ['Line charts showing the trend of ROSI over time.', 'Pie charts comparing the contribution of different sales activities to the overall ROSI.']
    ],
    risk_warnings=['A declining ROSI may indicate a need to reassess sales strategies and resource allocation.', 'High ROSI without corresponding revenue growth may suggest potential issues with pricing or cost management.'],
    
    # Tools & Integration
    suggested_tracking_tools=['Sales performance management software to track and analyze the effectiveness of sales activities.', 'Data analytics tools to identify patterns and correlations that impact ROSI.'],
    integration_points=['Integrate ROSI tracking with financial reporting systems to align sales performance with overall business goals.', 'Link ROSI with customer relationship management (CRM) systems to understand the impact of sales activities on customer satisfaction and retention.'],
    
    # Impact
    change_impact="Improving ROSI can lead to increased profitability and overall business performance. However, focusing solely on ROSI without considering customer satisfaction and long-term relationships may have negative impacts on brand reputation and customer loyalty.",
    
    # Metadata
    category="Business Development",
    is_active=True,
    metadata_={
        "modules": ["BUS_DEV"],
        "value_chains": ["SALES_MGMT"],
        "source": "kpidepot.com",
        "required_objects": ["Quarterly Business Review", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"]
    }
)
