"""
Sales per Representative KPI

The average amount of sales revenue generated by each sales representative, indicating individual performance.
"""

from analytics_models import KPI

SALES_PER_REPRESENTATIVE = KPI(
    name="Sales per Representative",
    code="SALES_PER_REPRESENTATIVE",
    category="Sales Performance",
    
    # Core Definition
    description="The average amount of sales revenue generated by each sales representative, indicating individual performance.",
    kpi_definition="The average amount of sales revenue generated by each sales representative, indicating individual performance.",
    expected_business_insights="Highlights individual sales performance and identifies areas for sales training and development.",
    measurement_approach="Measures the total sales made by each sales representative.",
    
    # Formula
    formula="Total Sales Revenue / Number of Sales Representatives",
    calculation_formula="Total Sales Revenue / Number of Sales Representatives",
    
    # Analysis
    trend_analysis="""
    * Increasing sales per representative may indicate improved sales techniques or increased demand for the product.
    * Decreasing sales per representative could signal a need for additional training or support for the sales team.
    """,
    diagnostic_questions="""
    * Are there specific products or services that certain representatives excel at selling?
    * How does the sales per representative compare to industry benchmarks or historical performance?
    """,
    
    # Action & Visualization
    actionable_tips="""
    * Provide ongoing training and support to help representatives improve their sales techniques.
    * Implement a mentorship program where high-performing representatives can share their strategies with others.
    * Regularly review and adjust sales territories to ensure equitable opportunities for all representatives.
    """,
    visualization_suggestions="""
    * Line charts showing the sales per representative over time to identify trends and patterns.
    * Pie charts comparing the contribution of each representative to the overall sales performance.
    """,
    
    # Risk & Integration
    risk_warnings="""
    * High sales per representative may lead to burnout or decreased job satisfaction if not managed properly.
    * Low sales per representative could indicate a need for changes in the sales team structure or strategy.
    """,
    tracking_tools="""
    * Customer relationship management (CRM) software to track individual sales performance and customer interactions.
    * Sales performance management platforms to set targets, track progress, and provide incentives for improvement.
    """,
    integration_points="""
    * Integrate sales per representative data with customer feedback and satisfaction scores to understand the impact of individual performance on customer relationships.
    * Link sales per representative with inventory management systems to ensure that representatives have the necessary products to sell.
    """,
    change_impact_analysis="""
    * Improving sales per representative can lead to increased revenue and customer satisfaction, but may also require additional resources for training and support.
    * Decreasing sales per representative could impact overall revenue and may require adjustments to the sales strategy or team structure.
    """,
    
    is_active=True,
    metadata_={
        "modules": ["SALES_PERFORMANCE"],
        "source": "kpidepot.com",
        "import_date": "2025-11-07",
        "required_objects": ["Customer", "Partner Performance Scorecard", "Performance Benchmark", "Performance Scorecard", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"]
    }
)
