"""
Revenue per Sales Representative KPI Definition
"""

REVENUE_PER_SALES_REPRESENTATIVE = {
    "code": "REVENUE_PER_SALES_REPRESENTATIVE",
    "name": "Revenue per Sales Representative",
    "display_name": "Revenue per Sales Representative",
    "description": "The amount of revenue generated by each sales representative, indicating their individual productivity and contribution to the team.",
    "formula": "Total Revenue / Number of Sales Representatives",
    "unit": "count",
    "category": "Business Development",
    "aggregation_methods": ["sum", "count"],
    "time_periods": ["daily", "weekly", "monthly", "quarterly", "annually"],
    "metadata_": {
        "modules": ["BUSINESS_DEVELOPMENT"],
        "required_objects": ["Product"]
    },
    "modules": ["BUSINESS_DEVELOPMENT"],
    "module_code": "BUSINESS_DEVELOPMENT",
}
