"""
Sales Pipeline Contribution KPI

The percentage of sales pipeline generated by the Sales Development team. It provides insight into how effectively the team is generating new opportunities for the sales team.
"""

SALES_PIPELINE_CONTRIBUTION = {
    "code": "SALES_PIPELINE_CONTRIBUTION",
    "name": "Sales Pipeline Contribution",
    "description": "The percentage of sales pipeline generated by the Sales Development team. It provides insight into how effectively the team is generating new opportunities for the sales team.",
    "formula": "Sum of Potential Revenue from All Opportunities in the Pipeline",
    "calculation_formula": "Sum of Potential Revenue from All Opportunities in the Pipeline",
    "category": "Sales Development",
    "is_active": True,
    "kpi_definition": "The percentage of sales pipeline generated by the Sales Development team. It provides insight into how effectively the team is generating new opportunities for the sales team.",
    "expected_business_insights": "Provides insight into future business and informs sales strategy and resource allocation.",
    "measurement_approach": "Tracks the amount of revenue in the sales pipeline and its potential contribution to total sales.",
    "trend_analysis": """
    * An increasing sales pipeline contribution may indicate improved lead generation efforts by the Sales Development team.
    * A decreasing contribution could signal a need for reevaluation of the team's prospecting strategies or a lack of alignment with the sales team's needs.
    """,
    "diagnostic_questions": """
    * Are there specific industries or market segments where the Sales Development team is particularly successful in generating pipeline?
    * How does the conversion rate from pipeline to closed deals compare to the overall pipeline contribution?
    """,
    "actionable_tips": """
    * Implement targeted outreach campaigns to industries or segments with high potential for pipeline generation.
    * Regularly review and update the ideal customer profile to ensure the Sales Development team is focusing on the most promising leads.
    * Provide ongoing training and coaching to improve the team's prospecting and qualification skills.
    """,
    "visualization_suggestions": """
    * Funnel charts to visualize the progression of leads through the pipeline stages.
    * Stacked bar charts comparing pipeline contribution by individual team members or by different lead sources.
    """,
    "risk_warnings": """
    * A low pipeline contribution may lead to a lack of opportunities for the sales team, impacting overall revenue generation.
    * An excessively high contribution without corresponding conversion rates could indicate a lack of quality in the leads being generated.
    """,
    "tracking_tools": """
    * Customer Relationship Management (CRM) software to track and analyze lead generation efforts and outcomes.
    * Sales enablement platforms to provide the Sales Development team with the necessary resources and content for effective prospecting.
    """,
    "integration_points": """
    * Integrate pipeline contribution data with sales performance metrics to understand the impact of the generated leads on actual revenue.
    * Link with marketing automation systems to align lead generation efforts with broader marketing strategies and campaigns.
    """,
    "change_impact_analysis": """
    * Increasing pipeline contribution can lead to higher sales volumes and revenue, but may also require additional resources to manage the increased workload.
    * On the other hand, a decrease in pipeline contribution can result in decreased sales opportunities and potential revenue, impacting overall business growth.
    """,
    "metadata_": {"modules": ["SALES_DEVELOPMENT"], "source": "kpidepot.com", "import_date": "2025-11-07", "required_objects": ["Customer", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Pipeline", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"]},
    "modules": ["SALES_DEVELOPMENT"],
    "module_code": "SALES_DEVELOPMENT",
}
