"""
Sales Growth KPI Definition
"""

SALES_GROWTH = {
    "code": "SALES_GROWTH",
    "name": "Sales Growth",
    "display_name": "Sales Growth",
    "description": "The percentage of revenue growth generated by the Business Development Team.",
    "formula": "",
    "unit": "count",
    "category": "Business Development",
    "metadata_": {
        "modules": ["BUSINESS_DEVELOPMENT"],
        "required_objects": []
    },
    "modules": ["BUSINESS_DEVELOPMENT"],
    "module_code": "BUSINESS_DEVELOPMENT",
}
