"""
Sales by Product Line KPI

The amount of sales generated by each product line.
"""

SALES_BY_PRODUCT_LINE = {
    "code": "SALES_BY_PRODUCT_LINE",
    "name": "Sales by Product Line",
    "description": "The amount of sales generated by each product line.",
    "formula": "Revenue attributed to each product line",
    "calculation_formula": "Revenue attributed to each product line",
    "category": "Sales Operations",
    "is_active": True,
    "kpi_definition": "The amount of sales generated by each product line.",
    "expected_business_insights": "Helps in understanding product demand and guiding inventory and production planning.",
    "measurement_approach": "Analyzes revenue attributed to different product lines.",
    "trend_analysis": """
    * Increasing sales by product line may indicate successful marketing efforts or new product launches.
    * Decreasing sales could signal market saturation or declining customer interest in certain product lines.
    """,
    "diagnostic_questions": """
    * Are there specific product lines that consistently outperform or underperform compared to others?
    * How do sales by product line align with overall market trends and customer preferences?
    """,
    "actionable_tips": """
    * Regularly review and update product line offerings to align with changing customer needs and market demands.
    * Invest in targeted marketing and sales strategies for underperforming product lines to boost sales.
    * Consider bundling or cross-selling strategies to increase sales across multiple product lines.
    """,
    "visualization_suggestions": """
    * Stacked bar charts to compare sales by product line over time.
    * Pie charts to visualize the percentage contribution of each product line to total sales.
    """,
    "risk_warnings": """
    * Over-reliance on a single product line for the majority of sales can pose a significant risk if market conditions change.
    * Underperforming product lines may lead to excess inventory and potential financial losses.
    """,
    "tracking_tools": """
    * Customer Relationship Management (CRM) software to track customer preferences and purchasing behavior by product line.
    * Business Intelligence (BI) tools to analyze sales data and identify trends and patterns across product lines.
    """,
    "integration_points": """
    * Integrate sales by product line data with inventory management systems to ensure adequate stock levels for high-performing products.
    * Link sales data with marketing automation platforms to tailor promotional efforts for different product lines.
    """,
    "change_impact_analysis": """
    * Increasing sales by product line can lead to improved revenue and profitability, but may also require additional resources for production and distribution.
    * Decreasing sales in certain product lines may necessitate strategic decisions such as discontinuation or repositioning of those products.
    """,
    "metadata_": {"modules": ["SALES_OPERATIONS"], "source": "kpidepot.com", "import_date": "2025-11-07", "required_objects": ["Customer", "Product", "Product Adoption", "Product Usage", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"]},
    "modules": ["SALES_OPERATIONS"],
    "module_code": "SALES_OPERATIONS",
}
