"""
Total Revenue KPI

The total amount of income generated from the sale of goods or services related to the company's primary operations.
"""

TOTAL_REVENUE = {
    "code": "TOTAL_REVENUE",
    "name": "Total Revenue",
    "description": "The total amount of income generated from the sale of goods or services related to the company's primary operations.",
    "formula": "Sum of All Revenue Streams",
    "calculation_formula": "Sum of All Revenue Streams",
    "category": "Sales Performance",
    "is_active": True,
    "kpi_definition": "The total amount of income generated from the sale of goods or services related to the company's primary operations.",
    "expected_business_insights": "Indicates the overall financial performance and is a baseline for many other KPIs.",
    "measurement_approach": "Considers all revenue generated by a company.",
    "trend_analysis": """
    * Increasing total revenue may indicate successful product launches or market expansion.
    * Decreasing revenue could signal market saturation or declining demand for existing products/services.
    """,
    "diagnostic_questions": """
    * Are there specific products or services driving the majority of the revenue, and are there opportunities to diversify offerings?
    * How does our revenue growth compare with industry benchmarks or economic trends?
    """,
    "actionable_tips": """
    * Explore new market segments or geographical areas to expand customer base.
    * Invest in marketing and sales strategies to promote existing products/services to new or existing customers.
    * Regularly review pricing strategies to ensure they align with market demand and competition.
    """,
    "visualization_suggestions": """
    * Line charts showing revenue trends over time.
    * Pie charts to visualize revenue distribution by product or service category.
    """,
    "risk_warnings": """
    * Reliance on a small number of high-revenue products/services can expose the business to significant risk if demand shifts.
    * Declining revenue may lead to financial instability and impact the ability to invest in future growth.
    """,
    "tracking_tools": """
    * Customer relationship management (CRM) systems to track and manage customer interactions and sales opportunities.
    * Business intelligence and analytics tools to identify revenue trends and customer behavior patterns.
    """,
    "integration_points": """
    * Integrate revenue data with marketing and sales systems to understand the impact of campaigns and promotions on revenue generation.
    * Link revenue tracking with financial systems to ensure accurate reporting and forecasting.
    """,
    "change_impact_analysis": """
    * Increasing revenue may require additional resources and investment in sales and marketing efforts.
    * Decreasing revenue can impact the ability to invest in research and development or expansion opportunities.
    """,
    "metadata_": {"modules": ["SALES_PERFORMANCE"], "source": "kpidepot.com", "import_date": "2025-11-07", "required_objects": ["Customer", "Lost Sale", "Partner Performance Scorecard", "Performance Benchmark", "Performance Scorecard", "Product", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"]},
    "modules": ["SALES_PERFORMANCE"],
    "module_code": "SALES_PERFORMANCE",
}
