"""add market_data table

Revision ID: d522b8986503
Revises: 
Create Date: 2025-09-27 23:40:53.823021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd522b8986503'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('database_service',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('ix_market_data_timestamp', 'market_data', ['timestamp'], unique=False)
    
    # Manually add the create_hypertable command for TimescaleDB
    op.execute("SELECT create_hypertable('market_data', 'timestamp');")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_data_timestamp', table_name='market_data')
    op.drop_table('market_data')
    # ### end Alembic commands ###
