"""
Meeting Booking Rate KPI

The rate at which initial sales calls or meetings are booked with potential clients.
"""

from analytics_models import KPI

MEETING_BOOKING_RATE = KPI(
    name="Meeting Booking Rate",
    code="MEETING_BOOKING_RATE",
    category="Sales Development",
    
    # Core Definition
    description="The rate at which initial sales calls or meetings are booked with potential clients.",
    kpi_definition="The rate at which initial sales calls or meetings are booked with potential clients.",
    expected_business_insights="Determines the effectiveness of outreach methods and sales engagement.",
    measurement_approach="Measures the success rate of booking meetings or appointments through various efforts.",
    
    # Formula
    formula="(Total Meetings Booked / Total Outreach Attempts) * 100",
    calculation_formula="(Total Meetings Booked / Total Outreach Attempts) * 100",
    
    # Analysis
    trend_analysis="""
    * An increasing meeting booking rate may indicate improved lead generation or a more effective sales outreach strategy.
    * A decreasing rate could signal a decline in the quality of leads or a need for sales process optimization.
    """,
    diagnostic_questions="""
    * Are there specific sales channels or sources that consistently yield higher meeting booking rates?
    * How does our meeting booking rate compare with industry benchmarks or historical performance?
    """,
    
    # Action & Visualization
    actionable_tips="""
    * Refine targeting and qualification criteria to focus on higher-potential leads.
    * Provide additional sales training and resources to improve the effectiveness of sales outreach efforts.
    * Implement a lead scoring system to prioritize leads with higher potential for meeting bookings.
    """,
    visualization_suggestions="""
    * Line charts showing the trend of meeting booking rates over time.
    * Pie charts to visualize the distribution of meeting bookings by sales channel or lead source.
    """,
    
    # Risk & Integration
    risk_warnings="""
    * A consistently low meeting booking rate can lead to missed sales opportunities and revenue loss.
    * A high meeting booking rate with low conversion rates may indicate a need for better lead qualification processes.
    """,
    tracking_tools="""
    * Customer Relationship Management (CRM) software to track and analyze lead interactions and meeting bookings.
    * Sales engagement platforms to streamline and optimize sales outreach activities.
    """,
    integration_points="""
    * Integrate meeting booking rate data with sales performance metrics to assess the impact on overall sales effectiveness.
    * Link meeting booking rate tracking with marketing analytics to understand the quality of leads generated by different marketing campaigns.
    """,
    change_impact_analysis="""
    * Improving the meeting booking rate can lead to increased sales opportunities and revenue growth.
    * However, a significant increase in meeting bookings without a corresponding increase in conversion rates may strain sales resources and affect overall sales productivity.
    """,
    
    is_active=True,
    metadata_={
        "modules": ["SALES_DEVELOPMENT"],
        "source": "kpidepot.com",
        "import_date": "2025-11-07",
        "required_objects": ["Call", "Customer", "Customer Success Manager", "Lead", "Meeting", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"]
    }
)
