"""
Revenue per Sales Representative KPI

Module: Business Development
"""

from analytics_models import KPI

REVENUE_PER_SALES_REPRESENTATIVE = KPI(
    name="Revenue per Sales Representative",
    code="REVENUE_PER_SALES_REPRESENTATIVE",
    description="The amount of revenue generated by each sales representative, indicating their individual productivity and contribution to the team.",
    
    # Definition & Context
    kpi_definition="The amount of revenue generated by each sales representative, indicating their individual productivity and contribution to the team.",
    expected_business_insights="Provides insights into individual sales performance and informs sales team management.",
    measurement_approach="Calculates the average revenue generated by each sales representative.",
    
    # Calculation
    formula="Total Revenue / Number of Sales Representatives",
    
    # Analysis
    trend_analysis="Increasing revenue per sales representative may indicate improved sales strategies or higher customer demand. Decreasing revenue per sales representative could signal issues with sales performance, market saturation, or changes in customer behavior.",
    diagnostic_questions=['What factors contribute to the variation in revenue generated by different sales representatives?', 'Are there specific products or services that certain sales representatives excel at selling?'],
    actionable_steps={
        "operational": ['Provide targeted training and support for sales representatives who may be struggling to meet revenue targets.'],
        "strategic": ['Implement a performance-based incentive structure to motivate sales representatives to increase their productivity.']
    },
    
    # Visualization
    visualization_suggestions=[
        {"type": "chart", "description": viz} for viz in ["Line charts tracking individual sales representatives' revenue over time to identify trends and outliers.", 'Comparison bar charts to visualize the revenue generated by each sales representative in a given period.']
    ],
    risk_warnings=['Low revenue per sales representative may lead to decreased team morale and motivation.', 'High revenue from a few top performers may mask overall team underperformance and limit growth potential.'],
    
    # Tools & Integration
    suggested_tracking_tools=['Customer Relationship Management (CRM) software to track individual sales performance and customer interactions.', 'Sales performance analytics tools to identify patterns and opportunities for improvement.'],
    integration_points=['Integrate revenue per sales representative data with customer feedback and satisfaction metrics to understand the impact of sales performance on customer relationships.', 'Link this KPI with marketing and lead generation data to assess the quality and quantity of leads provided to the sales team.'],
    
    # Impact
    change_impact="Improving revenue per sales representative can lead to increased overall company revenue and profitability. However, focusing solely on this KPI may neglect other important aspects of sales performance, such as customer retention and long-term relationship building.",
    
    # Metadata
    category="Business Development",
    is_active=True,
    metadata_={
        "modules": ["BUS_DEV", "SALES_DEVELOPMENT", "SALES_OPERATIONS", "SALES_PERFORMANCE", "SALES_STRATEGY"],
        "value_chains": ["SALES_MGMT"],
        "source": "kpidepot.com",
        "required_objects": ["Customer", "Product", "Quarterly Business Review", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program"],
        "replaces": ["SALES_PER_REPRESENTATIVE"]}
)
