"""
Sales Rep Productivity KPI

The average revenue generated by each sales rep. A higher revenue per rep indicates effective training and coaching.
"""

from analytics_models import KPI

SALES_REP_PRODUCTIVITY = KPI(
    name="Sales Rep Productivity",
    code="SALES_REP_PRODUCTIVITY",
    category="Sales Training and Coaching",
    
    # Core Definition
    description="The average revenue generated by each sales rep. A higher revenue per rep indicates effective training and coaching.",
    kpi_definition="The average revenue generated by each sales rep. A higher revenue per rep indicates effective training and coaching.",
    expected_business_insights="Reflects individual performance and can indicate the impact of training and coaching on sales efficiency.",
    measurement_approach="The amount of sales or revenue generated per rep within a certain timeframe.",
    
    # Formula
    formula="Total Sales or Revenue Generated / Number of Sales Reps",
    calculation_formula="Total Sales or Revenue Generated / Number of Sales Reps",
    
    # Analysis
    trend_analysis="""
    * An increasing sales rep productivity may indicate effective training and coaching methods, leading to improved performance.
    * A decreasing productivity could signal issues with training, coaching, or changes in the market that need to be addressed.
    """,
    diagnostic_questions="""
    * Are there specific sales techniques or strategies that have been particularly effective in driving higher productivity?
    * How does the productivity of top-performing sales reps compare to the average, and what can be learned from their methods?
    """,
    
    # Action & Visualization
    actionable_tips="""
    * Regularly review and update training materials to ensure they are relevant and effective.
    * Provide ongoing coaching and feedback to sales reps to help them continuously improve their skills and performance.
    * Implement a mentorship program where top-performing sales reps can share their knowledge and best practices with others.
    """,
    visualization_suggestions="""
    * Line charts showing the productivity of each sales rep over time to identify trends and outliers.
    * Comparison bar charts to visualize the differences in productivity between different teams or regions.
    """,
    
    # Risk & Integration
    risk_warnings="""
    * Low sales rep productivity can lead to missed revenue targets and decreased overall sales performance.
    * High productivity without proper training and coaching may result in burnout and decreased job satisfaction among sales reps.
    """,
    tracking_tools="""
    * Sales performance management software to track and analyze individual sales rep productivity and identify areas for improvement.
    * Learning management systems to deliver and track the effectiveness of training materials and courses.
    """,
    integration_points="""
    * Integrate sales rep productivity data with customer relationship management (CRM) systems to understand the relationship between productivity and customer interactions.
    * Link productivity metrics with sales incentive programs to align performance goals with compensation.
    """,
    change_impact_analysis="""
    * Improving sales rep productivity can lead to increased revenue and customer satisfaction, but may also require additional resources for training and coaching.
    * Decreasing productivity may indicate the need for changes in training and coaching methods, which could impact the overall sales strategy and performance.
    """,
    
    is_active=True,
    metadata_={
        "modules": ["SALES_TRAINING_COACHING"],
        "source": "kpidepot.com",
        "import_date": "2025-11-07",
        "required_objects": ["Coaching Session", "Customer", "Partner Training", "Product", "Revenue Forecast", "Sale", "Sales Activity", "Sales Appointment", "Sales Assessment", "Sales Call", "Sales Coaching Session", "Sales Content", "Sales Dashboard", "Sales Email", "Sales Forecast", "Sales Playbook", "Sales Process Workflow", "Sales Quota", "Sales Representative", "Sales Team", "Sales Territory", "Sales Training Program", "Training Program"]
    }
)
